import {
  DETAILED_TIME_SHEET_LEGEND_ITEMS,
  HOURLY_PAYROLL_LEGEND_ITEMS,
  WORK_SHEET_LEGEND_ITEMS,
} from '../constants/data';
import { TAB_KEYS, type LegendItem } from '../types/index.type';

export const TAB_LEGEND_MAP: Record<TAB_KEYS, LegendItem[]> = {
  [TAB_KEYS.WORKSHEET_BY_SHIFT]: WORK_SHEET_LEGEND_ITEMS,
  [TAB_KEYS.HOURLY_PAYROLL]: HOURLY_PAYROLL_LEGEND_ITEMS,
  [TAB_KEYS.DETAILED_TIME_SHEET]: DETAILED_TIME_SHEET_LEGEND_ITEMS,
};
