import {
  RecruitmentRequestStatusEnum,
  type MetadataRecruitmentRequest,
  type RecruitmentRequest,
} from '../types/type';

export const MOCK_METADATA: MetadataRecruitmentRequest = {
  totalAll: 10,
  totalRecruiting: 1,
  totalPending: 3,
  totalRejected: 1,
  totalApproved: 1,
  totalCancelled: 1,
  totalPaused: 1,
  totalClosed: 1,
};

const base = {
  departmentId: 'dept-1',
  departmentName: 'Khoa Răng hàm mặt',
  roomId: 'room-1',
  roomName: 'Phòng khám 1',
  position: 'Bác sĩ nội trú',
  quantity: 3,
  salaryRange: '12-15tr',
  requiredDate: '2027-01-01',
  workType: 'Fulltime',
  createdById: 'user-1',
  createdByName: 'Trần Minh',
  approvedById: null,
  approvedByName: null,
  approvedAt: null,
  rejectedReason: null,
  createdAt: '2025-12-01',
  updatedAt: '2025-12-15',
};

export const MOCK_RECRUITMENT_REQUESTS: RecruitmentRequest[] = [
  {
    ...base,
    id: '1',
    code: '3454564575',
    status: RecruitmentRequestStatusEnum.PENDING,
    candidateCount: 0,
    interviewCount: 0,
  },
  {
    ...base,
    id: '2',
    code: '3454564576',
    status: RecruitmentRequestStatusEnum.PENDING,
    candidateCount: 0,
    interviewCount: 0,
  },
  {
    ...base,
    id: '3',
    code: '3454564577',
    status: RecruitmentRequestStatusEnum.PENDING,
    candidateCount: 0,
    interviewCount: 0,
  },
  {
    ...base,
    id: '4',
    code: '3454564578',
    status: RecruitmentRequestStatusEnum.DRAFT,
    candidateCount: 0,
    interviewCount: 0,
  },
  {
    ...base,
    id: '5',
    code: '3454564579',
    departmentName: 'Khoa Ngoại',
    status: RecruitmentRequestStatusEnum.REJECTED,
    candidateCount: 0,
    interviewCount: 0,
    rejectedReason: 'Không đủ ngân sách',
  },
  {
    ...base,
    id: '6',
    code: '3454564580',
    departmentName: 'Khoa Nội',
    status: RecruitmentRequestStatusEnum.APPROVED,
    candidateCount: 0,
    interviewCount: 0,
  },
  {
    ...base,
    id: '7',
    code: '3454564581',
    status: RecruitmentRequestStatusEnum.RECRUITING,
    candidateCount: 55,
    interviewCount: 5,
  },
  {
    ...base,
    id: '8',
    code: '3454564582',
    status: RecruitmentRequestStatusEnum.PAUSED,
    candidateCount: 124,
    interviewCount: 23,
  },
  {
    ...base,
    id: '9',
    code: '3454564583',
    departmentName: 'Khoa Sản',
    status: RecruitmentRequestStatusEnum.CLOSED,
    candidateCount: 12,
    interviewCount: 3,
  },
  {
    ...base,
    id: '10',
    code: '3454564584',
    departmentName: 'Khoa Nội',
    status: RecruitmentRequestStatusEnum.CANCELLED,
    candidateCount: 0,
    interviewCount: 0,
  },
];
