import { RecruitmentRequestStatusEnum, type RecruitmentRequest } from '../type';

export const MOCK_RECRUITMENT_REQUESTS: RecruitmentRequest[] = [
  {
    id: '1',
    code: '3454564575',
    departmentId: 'dept-1',
    departmentName: 'Khoa Răng hàm mặt',
    roomId: 'room-1',
    roomName: 'Phòng khám 1',
    position: 'Bác sĩ nội trú',
    quantity: 3,
    salaryRange: '12-15tr',
    requiredDate: '2026-01-01',
    status: RecruitmentRequestStatusEnum.RECRUITING,
    workType: 'Fulltime',
    candidateCount: 55,
    interviewCount: 5,
    createdById: 'user-1',
    createdByName: 'Trần Minh',
    approvedById: null,
    approvedByName: null,
    approvedAt: null,
    rejectedReason: null,
    createdAt: '2025-12-01',
    updatedAt: '2025-12-15',
  },
  {
    id: '2',
    code: '3454564576',
    departmentId: 'dept-2',
    departmentName: 'Khoa Nội',
    roomId: 'room-2',
    roomName: 'Phòng khám 2',
    position: 'Bác sĩ nội trú',
    quantity: 3,
    salaryRange: '12-15tr',
    requiredDate: '2026-01-01',
    status: RecruitmentRequestStatusEnum.PENDING,
    workType: 'Fulltime',
    candidateCount: 0,
    interviewCount: 0,
    createdById: 'user-1',
    createdByName: 'Trần Minh',
    approvedById: null,
    approvedByName: null,
    approvedAt: null,
    rejectedReason: null,
    createdAt: '2025-12-01',
    updatedAt: '2025-12-15',
  },
  {
    id: '3',
    code: '3454564577',
    departmentId: 'dept-3',
    departmentName: 'Khoa Ngoại',
    roomId: 'room-3',
    roomName: 'Phòng mổ 1',
    position: 'Bác sĩ nội trú',
    quantity: 3,
    salaryRange: '12-15tr',
    requiredDate: '2026-01-01',
    status: RecruitmentRequestStatusEnum.CLOSED,
    workType: 'Fulltime',
    candidateCount: 12,
    interviewCount: 3,
    createdById: 'user-1',
    createdByName: 'Trần Minh',
    approvedById: null,
    approvedByName: null,
    approvedAt: null,
    rejectedReason: null,
    createdAt: '2025-12-01',
    updatedAt: '2025-12-15',
  },
  {
    id: '4',
    code: '3454564578',
    departmentId: 'dept-1',
    departmentName: 'Khoa Răng hàm mặt',
    roomId: 'room-1',
    roomName: 'Phòng khám 1',
    position: 'Bác sĩ nội trú',
    quantity: 3,
    salaryRange: '12-15tr',
    requiredDate: '2026-01-01',
    status: RecruitmentRequestStatusEnum.PAUSED,
    workType: 'Fulltime',
    candidateCount: 124,
    interviewCount: 23,
    createdById: 'user-1',
    createdByName: 'Trần Minh',
    approvedById: null,
    approvedByName: null,
    approvedAt: null,
    rejectedReason: null,
    createdAt: '2025-12-01',
    updatedAt: '2025-12-15',
  },
  {
    id: '5',
    code: '3454564579',
    departmentId: 'dept-4',
    departmentName: 'Khoa Sản',
    roomId: 'room-4',
    roomName: 'Phòng khám 3',
    position: 'Bác sĩ nội trú',
    quantity: 3,
    salaryRange: '12-15tr',
    requiredDate: '2026-01-01',
    status: RecruitmentRequestStatusEnum.DRAFT,
    workType: 'Fulltime',
    candidateCount: 0,
    interviewCount: 0,
    createdById: 'user-1',
    createdByName: 'Trần Minh',
    approvedById: null,
    approvedByName: null,
    approvedAt: null,
    rejectedReason: null,
    createdAt: '2025-12-01',
    updatedAt: '2025-12-15',
  },
  {
    id: '6',
    code: '3454564580',
    departmentId: 'dept-2',
    departmentName: 'Khoa Nội',
    roomId: 'room-2',
    roomName: 'Phòng khám 2',
    position: 'Bác sĩ nội trú',
    quantity: 3,
    salaryRange: '12-15tr',
    requiredDate: '2026-01-01',
    status: RecruitmentRequestStatusEnum.CANCELLED,
    workType: 'Fulltime',
    candidateCount: 0,
    interviewCount: 0,
    createdById: 'user-1',
    createdByName: 'Trần Minh',
    approvedById: null,
    approvedByName: null,
    approvedAt: null,
    rejectedReason: null,
    createdAt: '2025-12-01',
    updatedAt: '2025-12-15',
  },
  {
    id: '7',
    code: '3454564581',
    departmentId: 'dept-3',
    departmentName: 'Khoa Ngoại',
    roomId: 'room-3',
    roomName: 'Phòng mổ 1',
    position: 'Bác sĩ nội trú',
    quantity: 3,
    salaryRange: '12-15tr',
    requiredDate: '2026-01-01',
    status: RecruitmentRequestStatusEnum.REJECTED,
    workType: 'Fulltime',
    candidateCount: 0,
    interviewCount: 0,
    createdById: 'user-1',
    createdByName: 'Trần Minh',
    approvedById: null,
    approvedByName: null,
    approvedAt: null,
    rejectedReason: null,
    createdAt: '2025-12-01',
    updatedAt: '2025-12-15',
  },
  {
    id: '8',
    code: '3454564582',
    departmentId: 'dept-1',
    departmentName: 'Khoa Răng hàm mặt',
    roomId: 'room-1',
    roomName: 'Phòng khám 1',
    position: 'Bác sĩ nội trú',
    quantity: 3,
    salaryRange: '12-15tr',
    requiredDate: '2026-01-01',
    status: RecruitmentRequestStatusEnum.APPROVED,
    workType: 'Fulltime',
    candidateCount: 0,
    interviewCount: 0,
    createdById: 'user-1',
    createdByName: 'Trần Minh',
    approvedById: null,
    approvedByName: null,
    approvedAt: null,
    rejectedReason: null,
    createdAt: '2025-12-01',
    updatedAt: '2025-12-15',
  },
];
