
export const mockExplanationData: any[] = [
    {
        id: '1',
        departmentName: 'Khoa tai mũi họng',
        employeeCode: '23534546',
        employeeName: 'Pham Văn A',
        position: 'BA',
        date: '12/1/2026',
        errorType: 'Đi muộn',
        explanation: '7:30',
        attachmentName: 'Tên file.pdf',
        approverName: 'ALan Hanh',
        status: 'pending',
    },
    {
        id: '2',
        departmentName: 'Khoa tai mũi họng',
        employeeCode: '23534546',
        employeeName: 'Pham Văn A',
        position: 'BA',
        date: '12/1/2026',
        errorType: 'Đi muộn',
        explanation: '7:30',
        attachmentName: 'Tên file.pdf',
        approverName: 'ALan Hanh',
        status: 'pending',
    },
    {
        id: '3',
        departmentName: 'Khoa tai mũi họng',
        employeeCode: '23534546',
        employeeName: 'Pham Văn A',
        position: 'BA',
        date: '12/1/2026',
        errorType: 'Đi muộn',
        explanation: '7:30',
        attachmentName: 'Tên file.pdf',
        approverName: 'ALan Hanh',
        status: 'approved',
    },
    {
        id: '4',
        departmentName: 'Khoa tai mũi họng',
        employeeCode: '23534546',
        employeeName: 'Pham Văn A',
        position: 'BA',
        date: '12/1/2026',
        errorType: 'Đi muộn',
        explanation: '7:30',
        attachmentName: 'Tên file.pdf',
        approverName: 'ALan Hanh',
        status: 'approved',
    },
    {
        id: '5',
        departmentName: 'Khoa tai mũi họng',
        employeeCode: '23534546',
        employeeName: 'Pham Văn A',
        position: 'BA',
        date: '12/1/2026',
        errorType: 'Đi muộn',
        explanation: '7:30',
        attachmentName: 'Tên file.pdf',
        approverName: 'ALan Hanh',
        status: 'approved',
    },
    {
        id: '6',
        departmentName: 'Khoa tai mũi họng',
        employeeCode: '23534546',
        employeeName: 'Pham Văn A',
        position: 'BA',
        date: '12/1/2026',
        errorType: 'Đi muộn',
        explanation: '7:30',
        attachmentName: 'Tên file.pdf',
        approverName: 'ALan Hanh',
        status: 'approved',
    },
    {
        id: '7',
        departmentName: 'Khoa tai mũi họng',
        employeeCode: '23534546',
        employeeName: 'Pham Văn A',
        position: 'BA',
        date: '12/1/2026',
        errorType: 'Đi muộn',
        explanation: '7:30',
        attachmentName: 'Tên file.pdf',
        approverName: 'ALan Hanh',
        status: 'rejected',
    },
];

export const mockSummary: any = {
    totalRequests: 4,
    approved: 4,
    rejected: 4,
    pending: 4,
};

export const mockExplanationTypes: any[] = [
    { label: 'Nghỉ ốm', count: 4 },
    { label: 'Công tác', count: 12 },
    { label: 'Đi muộn', count: 24 },
];

export const statusOptions = [
    { key: 'ALL', label: 'Tất cả' },
    { key: 'PENDING', label: 'Chờ xác nhận' },
    { key: 'APPROVED', label: 'Đã xác nhận' },
    { key: 'REJECTED', label: 'Từ chối' },
];
