export const STAFF_FORM_DEFAULT_VALUES = {
    avatar: "",
    code: "",
    name: "",
    birthday: "",
    gender: "MALE",
    identity: "",
    identityIssueDate: null,
    identityIssuePlace: "",
    nationality: "Việt Nam",
    address: "",
    departmentIds: "",
    roomIds: "",
    workType: "",
    jobTitle: "",
    position: "",
    contractType: "",
    contractDuration: "",
    taxCode: "",
    insuranceNumber: "",
    healthInsuranceNumber: "",
    accountNumber: "",
    beneficiaryName: "",
    bankName: "",
    phone: "",
    email: "",
    emergencyContact: "",
    emergencyContactPhone: "",
    emergencyContactAddress: "",
    emergencyContactRelationship: "",
    qualification: "",
    major: "",
    academicTitles: [],
    certificateNumber: "",
    certificateIssuePlace: "",
    certificateExpiryDate: "",
    note: "",
    workingAreas: [{ departmentId: "", roomId: [] }],
};

export const STAFF_SECTION_KEYS = {
    AVATAR: "avatar",
    PERSONNEL: "personnel",
    DEPARTMENT: "department",
    ADDITIONAL: "additional",
    CONTACT: "contact",
    QUALIFICATION: "qualification",
    NOTES: "notes",
} as const;

