/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedRouteImport } from './routes/unauthenticated'
import { Route as AuthenticatedRouteImport } from './routes/authenticated'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivateLogoutRouteImport } from './routes/_private/logout'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as PrivateAdminIndexRouteImport } from './routes/_private/admin/index'
import { Route as AuthTimekeepingShiftSchedulingIndexRouteImport } from './routes/_auth/timekeeping-shift-scheduling/index'
import { Route as PrivateAdminDashboardRouteImport } from './routes/_private/admin/_dashboard'
import { Route as AuthTimekeepingShiftSchedulingTimekeepingManagementIndexRouteImport } from './routes/_auth/timekeeping-shift-scheduling/timekeeping-management/index'
import { Route as AuthTimekeepingShiftSchedulingShiftManagementIndexRouteImport } from './routes/_auth/timekeeping-shift-scheduling/shift-management/index'
import { Route as AuthTimekeepingShiftSchedulingExplanationManagementIndexRouteImport } from './routes/_auth/timekeeping-shift-scheduling/explanation-management/index'
import { Route as PrivateAdminDashboardTimekeepingShiftSchedulingIndexRouteImport } from './routes/_private/admin/_dashboard/timekeeping-shift-scheduling/index'
import { Route as PrivateAdminDashboardStaffManagementIndexRouteImport } from './routes/_private/admin/_dashboard/staff-management/index'
import { Route as PrivateAdminDashboardStaffManagementTypeRouteImport } from './routes/_private/admin/_dashboard/staff-management/$type'
import { Route as PrivateAdminDashboardTimekeepingShiftSchedulingShiftManagementIndexRouteImport } from './routes/_private/admin/_dashboard/timekeeping-shift-scheduling/shift-management/index'
import { Route as PrivateAdminDashboardTimekeepingShiftSchedulingExplanationManagementIndexRouteImport } from './routes/_private/admin/_dashboard/timekeeping-shift-scheduling/explanation-management/index'
import { Route as PrivateAdminDashboardStaffManagementDetailIdRouteImport } from './routes/_private/admin/_dashboard/staff-management/detail/$id'

const PrivateAdminDashboardDashboardLazyRouteImport = createFileRoute(
  '/_private/admin/_dashboard/dashboard',
)()
const PrivateAdminDashboardTimekeepingShiftSchedulingTimekeepingManagementIndexLazyRouteImport =
  createFileRoute(
    '/_private/admin/_dashboard/timekeeping-shift-scheduling/timekeeping-management/',
  )()

const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/unauthenticated',
  path: '/unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/authenticated',
  path: '/authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateLogoutRoute = PrivateLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => PrivateRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const PrivateAdminIndexRoute = PrivateAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => PrivateRoute,
} as any)
const AuthTimekeepingShiftSchedulingIndexRoute =
  AuthTimekeepingShiftSchedulingIndexRouteImport.update({
    id: '/timekeeping-shift-scheduling/',
    path: '/timekeeping-shift-scheduling/',
    getParentRoute: () => AuthRoute,
  } as any)
const PrivateAdminDashboardRoute = PrivateAdminDashboardRouteImport.update({
  id: '/admin/_dashboard',
  path: '/admin',
  getParentRoute: () => PrivateRoute,
} as any)
const AuthTimekeepingShiftSchedulingTimekeepingManagementIndexRoute =
  AuthTimekeepingShiftSchedulingTimekeepingManagementIndexRouteImport.update({
    id: '/timekeeping-shift-scheduling/timekeeping-management/',
    path: '/timekeeping-shift-scheduling/timekeeping-management/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthTimekeepingShiftSchedulingShiftManagementIndexRoute =
  AuthTimekeepingShiftSchedulingShiftManagementIndexRouteImport.update({
    id: '/timekeeping-shift-scheduling/shift-management/',
    path: '/timekeeping-shift-scheduling/shift-management/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthTimekeepingShiftSchedulingExplanationManagementIndexRoute =
  AuthTimekeepingShiftSchedulingExplanationManagementIndexRouteImport.update({
    id: '/timekeeping-shift-scheduling/explanation-management/',
    path: '/timekeeping-shift-scheduling/explanation-management/',
    getParentRoute: () => AuthRoute,
  } as any)
const PrivateAdminDashboardDashboardLazyRoute =
  PrivateAdminDashboardDashboardLazyRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => PrivateAdminDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_private/admin/_dashboard/dashboard.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateAdminDashboardTimekeepingShiftSchedulingIndexRoute =
  PrivateAdminDashboardTimekeepingShiftSchedulingIndexRouteImport.update({
    id: '/timekeeping-shift-scheduling/',
    path: '/timekeeping-shift-scheduling/',
    getParentRoute: () => PrivateAdminDashboardRoute,
  } as any)
const PrivateAdminDashboardStaffManagementIndexRoute =
  PrivateAdminDashboardStaffManagementIndexRouteImport.update({
    id: '/staff-management/',
    path: '/staff-management/',
    getParentRoute: () => PrivateAdminDashboardRoute,
  } as any)
const PrivateAdminDashboardStaffManagementTypeRoute =
  PrivateAdminDashboardStaffManagementTypeRouteImport.update({
    id: '/staff-management/$type',
    path: '/staff-management/$type',
    getParentRoute: () => PrivateAdminDashboardRoute,
  } as any)
const PrivateAdminDashboardTimekeepingShiftSchedulingTimekeepingManagementIndexLazyRoute =
  PrivateAdminDashboardTimekeepingShiftSchedulingTimekeepingManagementIndexLazyRouteImport.update(
    {
      id: '/timekeeping-shift-scheduling/timekeeping-management/',
      path: '/timekeeping-shift-scheduling/timekeeping-management/',
      getParentRoute: () => PrivateAdminDashboardRoute,
    } as any,
  ).lazy(() =>
    import('./routes/_private/admin/_dashboard/timekeeping-shift-scheduling/timekeeping-management/index.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateAdminDashboardTimekeepingShiftSchedulingShiftManagementIndexRoute =
  PrivateAdminDashboardTimekeepingShiftSchedulingShiftManagementIndexRouteImport.update(
    {
      id: '/timekeeping-shift-scheduling/shift-management/',
      path: '/timekeeping-shift-scheduling/shift-management/',
      getParentRoute: () => PrivateAdminDashboardRoute,
    } as any,
  )
const PrivateAdminDashboardTimekeepingShiftSchedulingExplanationManagementIndexRoute =
  PrivateAdminDashboardTimekeepingShiftSchedulingExplanationManagementIndexRouteImport.update(
    {
      id: '/timekeeping-shift-scheduling/explanation-management/',
      path: '/timekeeping-shift-scheduling/explanation-management/',
      getParentRoute: () => PrivateAdminDashboardRoute,
    } as any,
  )
const PrivateAdminDashboardStaffManagementDetailIdRoute =
  PrivateAdminDashboardStaffManagementDetailIdRouteImport.update({
    id: '/staff-management/detail/$id',
    path: '/staff-management/detail/$id',
    getParentRoute: () => PrivateAdminDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authenticated': typeof AuthenticatedRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/login': typeof AuthLoginRoute
  '/logout': typeof PrivateLogoutRoute
  '/admin': typeof PrivateAdminDashboardRouteWithChildren
  '/timekeeping-shift-scheduling/': typeof AuthTimekeepingShiftSchedulingIndexRoute
  '/admin/': typeof PrivateAdminIndexRoute
  '/admin/dashboard': typeof PrivateAdminDashboardDashboardLazyRoute
  '/timekeeping-shift-scheduling/explanation-management/': typeof AuthTimekeepingShiftSchedulingExplanationManagementIndexRoute
  '/timekeeping-shift-scheduling/shift-management/': typeof AuthTimekeepingShiftSchedulingShiftManagementIndexRoute
  '/timekeeping-shift-scheduling/timekeeping-management/': typeof AuthTimekeepingShiftSchedulingTimekeepingManagementIndexRoute
  '/admin/staff-management/$type': typeof PrivateAdminDashboardStaffManagementTypeRoute
  '/admin/staff-management/': typeof PrivateAdminDashboardStaffManagementIndexRoute
  '/admin/timekeeping-shift-scheduling/': typeof PrivateAdminDashboardTimekeepingShiftSchedulingIndexRoute
  '/admin/staff-management/detail/$id': typeof PrivateAdminDashboardStaffManagementDetailIdRoute
  '/admin/timekeeping-shift-scheduling/explanation-management/': typeof PrivateAdminDashboardTimekeepingShiftSchedulingExplanationManagementIndexRoute
  '/admin/timekeeping-shift-scheduling/shift-management/': typeof PrivateAdminDashboardTimekeepingShiftSchedulingShiftManagementIndexRoute
  '/admin/timekeeping-shift-scheduling/timekeeping-management/': typeof PrivateAdminDashboardTimekeepingShiftSchedulingTimekeepingManagementIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authenticated': typeof AuthenticatedRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/login': typeof AuthLoginRoute
  '/logout': typeof PrivateLogoutRoute
  '/admin': typeof PrivateAdminIndexRoute
  '/timekeeping-shift-scheduling': typeof AuthTimekeepingShiftSchedulingIndexRoute
  '/admin/dashboard': typeof PrivateAdminDashboardDashboardLazyRoute
  '/timekeeping-shift-scheduling/explanation-management': typeof AuthTimekeepingShiftSchedulingExplanationManagementIndexRoute
  '/timekeeping-shift-scheduling/shift-management': typeof AuthTimekeepingShiftSchedulingShiftManagementIndexRoute
  '/timekeeping-shift-scheduling/timekeeping-management': typeof AuthTimekeepingShiftSchedulingTimekeepingManagementIndexRoute
  '/admin/staff-management/$type': typeof PrivateAdminDashboardStaffManagementTypeRoute
  '/admin/staff-management': typeof PrivateAdminDashboardStaffManagementIndexRoute
  '/admin/timekeeping-shift-scheduling': typeof PrivateAdminDashboardTimekeepingShiftSchedulingIndexRoute
  '/admin/staff-management/detail/$id': typeof PrivateAdminDashboardStaffManagementDetailIdRoute
  '/admin/timekeeping-shift-scheduling/explanation-management': typeof PrivateAdminDashboardTimekeepingShiftSchedulingExplanationManagementIndexRoute
  '/admin/timekeeping-shift-scheduling/shift-management': typeof PrivateAdminDashboardTimekeepingShiftSchedulingShiftManagementIndexRoute
  '/admin/timekeeping-shift-scheduling/timekeeping-management': typeof PrivateAdminDashboardTimekeepingShiftSchedulingTimekeepingManagementIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_private': typeof PrivateRouteWithChildren
  '/authenticated': typeof AuthenticatedRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_private/logout': typeof PrivateLogoutRoute
  '/_private/admin/_dashboard': typeof PrivateAdminDashboardRouteWithChildren
  '/_auth/timekeeping-shift-scheduling/': typeof AuthTimekeepingShiftSchedulingIndexRoute
  '/_private/admin/': typeof PrivateAdminIndexRoute
  '/_private/admin/_dashboard/dashboard': typeof PrivateAdminDashboardDashboardLazyRoute
  '/_auth/timekeeping-shift-scheduling/explanation-management/': typeof AuthTimekeepingShiftSchedulingExplanationManagementIndexRoute
  '/_auth/timekeeping-shift-scheduling/shift-management/': typeof AuthTimekeepingShiftSchedulingShiftManagementIndexRoute
  '/_auth/timekeeping-shift-scheduling/timekeeping-management/': typeof AuthTimekeepingShiftSchedulingTimekeepingManagementIndexRoute
  '/_private/admin/_dashboard/staff-management/$type': typeof PrivateAdminDashboardStaffManagementTypeRoute
  '/_private/admin/_dashboard/staff-management/': typeof PrivateAdminDashboardStaffManagementIndexRoute
  '/_private/admin/_dashboard/timekeeping-shift-scheduling/': typeof PrivateAdminDashboardTimekeepingShiftSchedulingIndexRoute
  '/_private/admin/_dashboard/staff-management/detail/$id': typeof PrivateAdminDashboardStaffManagementDetailIdRoute
  '/_private/admin/_dashboard/timekeeping-shift-scheduling/explanation-management/': typeof PrivateAdminDashboardTimekeepingShiftSchedulingExplanationManagementIndexRoute
  '/_private/admin/_dashboard/timekeeping-shift-scheduling/shift-management/': typeof PrivateAdminDashboardTimekeepingShiftSchedulingShiftManagementIndexRoute
  '/_private/admin/_dashboard/timekeeping-shift-scheduling/timekeeping-management/': typeof PrivateAdminDashboardTimekeepingShiftSchedulingTimekeepingManagementIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authenticated'
    | '/unauthenticated'
    | '/login'
    | '/logout'
    | '/admin'
    | '/timekeeping-shift-scheduling/'
    | '/admin/'
    | '/admin/dashboard'
    | '/timekeeping-shift-scheduling/explanation-management/'
    | '/timekeeping-shift-scheduling/shift-management/'
    | '/timekeeping-shift-scheduling/timekeeping-management/'
    | '/admin/staff-management/$type'
    | '/admin/staff-management/'
    | '/admin/timekeeping-shift-scheduling/'
    | '/admin/staff-management/detail/$id'
    | '/admin/timekeeping-shift-scheduling/explanation-management/'
    | '/admin/timekeeping-shift-scheduling/shift-management/'
    | '/admin/timekeeping-shift-scheduling/timekeeping-management/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authenticated'
    | '/unauthenticated'
    | '/login'
    | '/logout'
    | '/admin'
    | '/timekeeping-shift-scheduling'
    | '/admin/dashboard'
    | '/timekeeping-shift-scheduling/explanation-management'
    | '/timekeeping-shift-scheduling/shift-management'
    | '/timekeeping-shift-scheduling/timekeeping-management'
    | '/admin/staff-management/$type'
    | '/admin/staff-management'
    | '/admin/timekeeping-shift-scheduling'
    | '/admin/staff-management/detail/$id'
    | '/admin/timekeeping-shift-scheduling/explanation-management'
    | '/admin/timekeeping-shift-scheduling/shift-management'
    | '/admin/timekeeping-shift-scheduling/timekeeping-management'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_private'
    | '/authenticated'
    | '/unauthenticated'
    | '/_auth/login'
    | '/_private/logout'
    | '/_private/admin/_dashboard'
    | '/_auth/timekeeping-shift-scheduling/'
    | '/_private/admin/'
    | '/_private/admin/_dashboard/dashboard'
    | '/_auth/timekeeping-shift-scheduling/explanation-management/'
    | '/_auth/timekeeping-shift-scheduling/shift-management/'
    | '/_auth/timekeeping-shift-scheduling/timekeeping-management/'
    | '/_private/admin/_dashboard/staff-management/$type'
    | '/_private/admin/_dashboard/staff-management/'
    | '/_private/admin/_dashboard/timekeeping-shift-scheduling/'
    | '/_private/admin/_dashboard/staff-management/detail/$id'
    | '/_private/admin/_dashboard/timekeeping-shift-scheduling/explanation-management/'
    | '/_private/admin/_dashboard/timekeeping-shift-scheduling/shift-management/'
    | '/_private/admin/_dashboard/timekeeping-shift-scheduling/timekeeping-management/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  PrivateRoute: typeof PrivateRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRoute
  UnauthenticatedRoute: typeof UnauthenticatedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthenticated': {
      id: '/unauthenticated'
      path: '/unauthenticated'
      fullPath: '/unauthenticated'
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticated': {
      id: '/authenticated'
      path: '/authenticated'
      fullPath: '/authenticated'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/logout': {
      id: '/_private/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof PrivateLogoutRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_private/admin/': {
      id: '/_private/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof PrivateAdminIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_auth/timekeeping-shift-scheduling/': {
      id: '/_auth/timekeeping-shift-scheduling/'
      path: '/timekeeping-shift-scheduling'
      fullPath: '/timekeeping-shift-scheduling/'
      preLoaderRoute: typeof AuthTimekeepingShiftSchedulingIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_private/admin/_dashboard': {
      id: '/_private/admin/_dashboard'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof PrivateAdminDashboardRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_auth/timekeeping-shift-scheduling/timekeeping-management/': {
      id: '/_auth/timekeeping-shift-scheduling/timekeeping-management/'
      path: '/timekeeping-shift-scheduling/timekeeping-management'
      fullPath: '/timekeeping-shift-scheduling/timekeeping-management/'
      preLoaderRoute: typeof AuthTimekeepingShiftSchedulingTimekeepingManagementIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/timekeeping-shift-scheduling/shift-management/': {
      id: '/_auth/timekeeping-shift-scheduling/shift-management/'
      path: '/timekeeping-shift-scheduling/shift-management'
      fullPath: '/timekeeping-shift-scheduling/shift-management/'
      preLoaderRoute: typeof AuthTimekeepingShiftSchedulingShiftManagementIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/timekeeping-shift-scheduling/explanation-management/': {
      id: '/_auth/timekeeping-shift-scheduling/explanation-management/'
      path: '/timekeeping-shift-scheduling/explanation-management'
      fullPath: '/timekeeping-shift-scheduling/explanation-management/'
      preLoaderRoute: typeof AuthTimekeepingShiftSchedulingExplanationManagementIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_private/admin/_dashboard/dashboard': {
      id: '/_private/admin/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof PrivateAdminDashboardDashboardLazyRouteImport
      parentRoute: typeof PrivateAdminDashboardRoute
    }
    '/_private/admin/_dashboard/timekeeping-shift-scheduling/': {
      id: '/_private/admin/_dashboard/timekeeping-shift-scheduling/'
      path: '/timekeeping-shift-scheduling'
      fullPath: '/admin/timekeeping-shift-scheduling/'
      preLoaderRoute: typeof PrivateAdminDashboardTimekeepingShiftSchedulingIndexRouteImport
      parentRoute: typeof PrivateAdminDashboardRoute
    }
    '/_private/admin/_dashboard/staff-management/': {
      id: '/_private/admin/_dashboard/staff-management/'
      path: '/staff-management'
      fullPath: '/admin/staff-management/'
      preLoaderRoute: typeof PrivateAdminDashboardStaffManagementIndexRouteImport
      parentRoute: typeof PrivateAdminDashboardRoute
    }
    '/_private/admin/_dashboard/staff-management/$type': {
      id: '/_private/admin/_dashboard/staff-management/$type'
      path: '/staff-management/$type'
      fullPath: '/admin/staff-management/$type'
      preLoaderRoute: typeof PrivateAdminDashboardStaffManagementTypeRouteImport
      parentRoute: typeof PrivateAdminDashboardRoute
    }
    '/_private/admin/_dashboard/timekeeping-shift-scheduling/timekeeping-management/': {
      id: '/_private/admin/_dashboard/timekeeping-shift-scheduling/timekeeping-management/'
      path: '/timekeeping-shift-scheduling/timekeeping-management'
      fullPath: '/admin/timekeeping-shift-scheduling/timekeeping-management/'
      preLoaderRoute: typeof PrivateAdminDashboardTimekeepingShiftSchedulingTimekeepingManagementIndexLazyRouteImport
      parentRoute: typeof PrivateAdminDashboardRoute
    }
    '/_private/admin/_dashboard/timekeeping-shift-scheduling/shift-management/': {
      id: '/_private/admin/_dashboard/timekeeping-shift-scheduling/shift-management/'
      path: '/timekeeping-shift-scheduling/shift-management'
      fullPath: '/admin/timekeeping-shift-scheduling/shift-management/'
      preLoaderRoute: typeof PrivateAdminDashboardTimekeepingShiftSchedulingShiftManagementIndexRouteImport
      parentRoute: typeof PrivateAdminDashboardRoute
    }
    '/_private/admin/_dashboard/timekeeping-shift-scheduling/explanation-management/': {
      id: '/_private/admin/_dashboard/timekeeping-shift-scheduling/explanation-management/'
      path: '/timekeeping-shift-scheduling/explanation-management'
      fullPath: '/admin/timekeeping-shift-scheduling/explanation-management/'
      preLoaderRoute: typeof PrivateAdminDashboardTimekeepingShiftSchedulingExplanationManagementIndexRouteImport
      parentRoute: typeof PrivateAdminDashboardRoute
    }
    '/_private/admin/_dashboard/staff-management/detail/$id': {
      id: '/_private/admin/_dashboard/staff-management/detail/$id'
      path: '/staff-management/detail/$id'
      fullPath: '/admin/staff-management/detail/$id'
      preLoaderRoute: typeof PrivateAdminDashboardStaffManagementDetailIdRouteImport
      parentRoute: typeof PrivateAdminDashboardRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthTimekeepingShiftSchedulingIndexRoute: typeof AuthTimekeepingShiftSchedulingIndexRoute
  AuthTimekeepingShiftSchedulingExplanationManagementIndexRoute: typeof AuthTimekeepingShiftSchedulingExplanationManagementIndexRoute
  AuthTimekeepingShiftSchedulingShiftManagementIndexRoute: typeof AuthTimekeepingShiftSchedulingShiftManagementIndexRoute
  AuthTimekeepingShiftSchedulingTimekeepingManagementIndexRoute: typeof AuthTimekeepingShiftSchedulingTimekeepingManagementIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthTimekeepingShiftSchedulingIndexRoute:
    AuthTimekeepingShiftSchedulingIndexRoute,
  AuthTimekeepingShiftSchedulingExplanationManagementIndexRoute:
    AuthTimekeepingShiftSchedulingExplanationManagementIndexRoute,
  AuthTimekeepingShiftSchedulingShiftManagementIndexRoute:
    AuthTimekeepingShiftSchedulingShiftManagementIndexRoute,
  AuthTimekeepingShiftSchedulingTimekeepingManagementIndexRoute:
    AuthTimekeepingShiftSchedulingTimekeepingManagementIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PrivateAdminDashboardRouteChildren {
  PrivateAdminDashboardDashboardLazyRoute: typeof PrivateAdminDashboardDashboardLazyRoute
  PrivateAdminDashboardStaffManagementTypeRoute: typeof PrivateAdminDashboardStaffManagementTypeRoute
  PrivateAdminDashboardStaffManagementIndexRoute: typeof PrivateAdminDashboardStaffManagementIndexRoute
  PrivateAdminDashboardTimekeepingShiftSchedulingIndexRoute: typeof PrivateAdminDashboardTimekeepingShiftSchedulingIndexRoute
  PrivateAdminDashboardStaffManagementDetailIdRoute: typeof PrivateAdminDashboardStaffManagementDetailIdRoute
  PrivateAdminDashboardTimekeepingShiftSchedulingExplanationManagementIndexRoute: typeof PrivateAdminDashboardTimekeepingShiftSchedulingExplanationManagementIndexRoute
  PrivateAdminDashboardTimekeepingShiftSchedulingShiftManagementIndexRoute: typeof PrivateAdminDashboardTimekeepingShiftSchedulingShiftManagementIndexRoute
  PrivateAdminDashboardTimekeepingShiftSchedulingTimekeepingManagementIndexLazyRoute: typeof PrivateAdminDashboardTimekeepingShiftSchedulingTimekeepingManagementIndexLazyRoute
}

const PrivateAdminDashboardRouteChildren: PrivateAdminDashboardRouteChildren = {
  PrivateAdminDashboardDashboardLazyRoute:
    PrivateAdminDashboardDashboardLazyRoute,
  PrivateAdminDashboardStaffManagementTypeRoute:
    PrivateAdminDashboardStaffManagementTypeRoute,
  PrivateAdminDashboardStaffManagementIndexRoute:
    PrivateAdminDashboardStaffManagementIndexRoute,
  PrivateAdminDashboardTimekeepingShiftSchedulingIndexRoute:
    PrivateAdminDashboardTimekeepingShiftSchedulingIndexRoute,
  PrivateAdminDashboardStaffManagementDetailIdRoute:
    PrivateAdminDashboardStaffManagementDetailIdRoute,
  PrivateAdminDashboardTimekeepingShiftSchedulingExplanationManagementIndexRoute:
    PrivateAdminDashboardTimekeepingShiftSchedulingExplanationManagementIndexRoute,
  PrivateAdminDashboardTimekeepingShiftSchedulingShiftManagementIndexRoute:
    PrivateAdminDashboardTimekeepingShiftSchedulingShiftManagementIndexRoute,
  PrivateAdminDashboardTimekeepingShiftSchedulingTimekeepingManagementIndexLazyRoute:
    PrivateAdminDashboardTimekeepingShiftSchedulingTimekeepingManagementIndexLazyRoute,
}

const PrivateAdminDashboardRouteWithChildren =
  PrivateAdminDashboardRoute._addFileChildren(
    PrivateAdminDashboardRouteChildren,
  )

interface PrivateRouteChildren {
  PrivateLogoutRoute: typeof PrivateLogoutRoute
  PrivateAdminDashboardRoute: typeof PrivateAdminDashboardRouteWithChildren
  PrivateAdminIndexRoute: typeof PrivateAdminIndexRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateLogoutRoute: PrivateLogoutRoute,
  PrivateAdminDashboardRoute: PrivateAdminDashboardRouteWithChildren,
  PrivateAdminIndexRoute: PrivateAdminIndexRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  PrivateRoute: PrivateRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRoute,
  UnauthenticatedRoute: UnauthenticatedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
