/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/authenticated'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivateLogoutRouteImport } from './routes/_private/logout'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as PrivateAdminIndexRouteImport } from './routes/_private/admin/index'
import { Route as PrivateAdminDashboardRouteImport } from './routes/_private/admin/_dashboard'

const PrivateAdminDashboardDashboardLazyRouteImport = createFileRoute(
  '/_private/admin/_dashboard/dashboard',
)()

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/authenticated',
  path: '/authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateLogoutRoute = PrivateLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => PrivateRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const PrivateAdminIndexRoute = PrivateAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateAdminDashboardRoute = PrivateAdminDashboardRouteImport.update({
  id: '/admin/_dashboard',
  path: '/admin',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateAdminDashboardDashboardLazyRoute =
  PrivateAdminDashboardDashboardLazyRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => PrivateAdminDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_private/admin/_dashboard/dashboard.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authenticated': typeof AuthenticatedRoute
  '/login': typeof AuthLoginRoute
  '/logout': typeof PrivateLogoutRoute
  '/admin': typeof PrivateAdminIndexRoute
  '/admin/dashboard': typeof PrivateAdminDashboardDashboardLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authenticated': typeof AuthenticatedRoute
  '/login': typeof AuthLoginRoute
  '/logout': typeof PrivateLogoutRoute
  '/admin': typeof PrivateAdminIndexRoute
  '/admin/dashboard': typeof PrivateAdminDashboardDashboardLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_private': typeof PrivateRouteWithChildren
  '/authenticated': typeof AuthenticatedRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_private/logout': typeof PrivateLogoutRoute
  '/_private/admin/_dashboard': typeof PrivateAdminDashboardRouteWithChildren
  '/_private/admin/': typeof PrivateAdminIndexRoute
  '/_private/admin/_dashboard/dashboard': typeof PrivateAdminDashboardDashboardLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authenticated'
    | '/login'
    | '/logout'
    | '/admin'
    | '/admin/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authenticated'
    | '/login'
    | '/logout'
    | '/admin'
    | '/admin/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_private'
    | '/authenticated'
    | '/_auth/login'
    | '/_private/logout'
    | '/_private/admin/_dashboard'
    | '/_private/admin/'
    | '/_private/admin/_dashboard/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  PrivateRoute: typeof PrivateRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/authenticated': {
      id: '/authenticated'
      path: '/authenticated'
      fullPath: '/authenticated'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/logout': {
      id: '/_private/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof PrivateLogoutRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_private/admin/': {
      id: '/_private/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof PrivateAdminIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/admin/_dashboard': {
      id: '/_private/admin/_dashboard'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof PrivateAdminDashboardRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/admin/_dashboard/dashboard': {
      id: '/_private/admin/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof PrivateAdminDashboardDashboardLazyRouteImport
      parentRoute: typeof PrivateAdminDashboardRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PrivateAdminDashboardRouteChildren {
  PrivateAdminDashboardDashboardLazyRoute: typeof PrivateAdminDashboardDashboardLazyRoute
}

const PrivateAdminDashboardRouteChildren: PrivateAdminDashboardRouteChildren = {
  PrivateAdminDashboardDashboardLazyRoute:
    PrivateAdminDashboardDashboardLazyRoute,
}

const PrivateAdminDashboardRouteWithChildren =
  PrivateAdminDashboardRoute._addFileChildren(
    PrivateAdminDashboardRouteChildren,
  )

interface PrivateRouteChildren {
  PrivateLogoutRoute: typeof PrivateLogoutRoute
  PrivateAdminDashboardRoute: typeof PrivateAdminDashboardRouteWithChildren
  PrivateAdminIndexRoute: typeof PrivateAdminIndexRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateLogoutRoute: PrivateLogoutRoute,
  PrivateAdminDashboardRoute: PrivateAdminDashboardRouteWithChildren,
  PrivateAdminIndexRoute: PrivateAdminIndexRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  PrivateRoute: PrivateRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
