/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedRouteImport } from './routes/unauthenticated'
import { Route as AuthenticatedRouteImport } from './routes/authenticated'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivateLogoutRouteImport } from './routes/_private/logout'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as PrivateAdminIndexRouteImport } from './routes/_private/admin/index'
import { Route as AuthTimekeepingShiftSchedulingIndexRouteImport } from './routes/_auth/timekeeping-shift-scheduling/index'
import { Route as PrivateAdminDashboardRouteImport } from './routes/_private/admin/_dashboard'
import { Route as AuthTimekeepingShiftSchedulingTimekeepingManagementIndexRouteImport } from './routes/_auth/timekeeping-shift-scheduling/timekeeping-management/index'
import { Route as AuthTimekeepingShiftSchedulingShiftManagementIndexRouteImport } from './routes/_auth/timekeeping-shift-scheduling/shift-management/index'
import { Route as AuthTimekeepingShiftSchedulingExplanationManagementIndexRouteImport } from './routes/_auth/timekeeping-shift-scheduling/explanation-management/index'
import { Route as PrivateAdminDashboardTimekeepingShiftSchedulingIndexRouteImport } from './routes/_private/admin/_dashboard/timekeeping-shift-scheduling/index'
import { Route as PrivateAdminDashboardStaffManagementIndexRouteImport } from './routes/_private/admin/_dashboard/staff-management/index'
import { Route as PrivateAdminDashboardRecruitmentManagementIndexRouteImport } from './routes/_private/admin/_dashboard/recruitment-management/index'
import { Route as PrivateAdminDashboardPayrollManagementIndexRouteImport } from './routes/_private/admin/_dashboard/payroll-management/index'
import { Route as PrivateAdminDashboardOtherRequestsManagementIndexRouteImport } from './routes/_private/admin/_dashboard/other-requests-management/index'
import { Route as PrivateAdminDashboardManagementReportIndexRouteImport } from './routes/_private/admin/_dashboard/management-report/index'
import { Route as PrivateAdminDashboardLeaveManagementIndexRouteImport } from './routes/_private/admin/_dashboard/leave-management/index'
import { Route as PrivateAdminDashboardContractManagementIndexRouteImport } from './routes/_private/admin/_dashboard/contract-management/index'
import { Route as PrivateAdminDashboardStaffManagementTypeRouteImport } from './routes/_private/admin/_dashboard/staff-management/$type'
import { Route as PrivateAdminDashboardPayrollManagementSalaryHistoryRouteImport } from './routes/_private/admin/_dashboard/payroll-management/salary-history'
import { Route as PrivateAdminDashboardPayrollManagementPayslipFeedbackRouteImport } from './routes/_private/admin/_dashboard/payroll-management/payslip-feedback'
import { Route as PrivateAdminDashboardPayrollManagementPayrollCalculationRouteImport } from './routes/_private/admin/_dashboard/payroll-management/payroll-calculation'
import { Route as PrivateAdminDashboardOtherRequestsManagementTrainingRegistrationRanagementRouteImport } from './routes/_private/admin/_dashboard/other-requests-management/training-registration-ranagement'
import { Route as PrivateAdminDashboardOtherRequestsManagementRemoteWorkManagementRouteImport } from './routes/_private/admin/_dashboard/other-requests-management/remote-work-management'
import { Route as PrivateAdminDashboardOtherRequestsManagementOvertimeManagementRouteImport } from './routes/_private/admin/_dashboard/other-requests-management/overtime-management'
import { Route as PrivateAdminDashboardOtherRequestsManagementBusinessTripManagementRouteImport } from './routes/_private/admin/_dashboard/other-requests-management/business-trip-management'
import { Route as PrivateAdminDashboardLeaveManagementLeaveRequestManagementRouteImport } from './routes/_private/admin/_dashboard/leave-management/leave-request-management'
import { Route as PrivateAdminDashboardPayrollManagementDataSummaryRouteRouteImport } from './routes/_private/admin/_dashboard/payroll-management/data-summary/route'
import { Route as PrivateAdminDashboardTimekeepingShiftSchedulingTimekeepingManagementIndexRouteImport } from './routes/_private/admin/_dashboard/timekeeping-shift-scheduling/timekeeping-management/index'
import { Route as PrivateAdminDashboardTimekeepingShiftSchedulingShiftManagementIndexRouteImport } from './routes/_private/admin/_dashboard/timekeeping-shift-scheduling/shift-management/index'
import { Route as PrivateAdminDashboardTimekeepingShiftSchedulingExplanationManagementIndexRouteImport } from './routes/_private/admin/_dashboard/timekeeping-shift-scheduling/explanation-management/index'
import { Route as PrivateAdminDashboardPayrollManagementDataSummaryIndexRouteImport } from './routes/_private/admin/_dashboard/payroll-management/data-summary/index'
import { Route as PrivateAdminDashboardStaffManagementDetailIdRouteImport } from './routes/_private/admin/_dashboard/staff-management/detail/$id'
import { Route as PrivateAdminDashboardPayrollManagementDataSummarySummaryFinalizeIndexRouteImport } from './routes/_private/admin/_dashboard/payroll-management/data-summary/summary-finalize/index'
import { Route as PrivateAdminDashboardPayrollManagementDataSummaryRevenueIndexRouteImport } from './routes/_private/admin/_dashboard/payroll-management/data-summary/revenue/index'
import { Route as PrivateAdminDashboardPayrollManagementDataSummaryOtherIncomeIndexRouteImport } from './routes/_private/admin/_dashboard/payroll-management/data-summary/other-income/index'
import { Route as PrivateAdminDashboardPayrollManagementDataSummaryKpiIndexRouteImport } from './routes/_private/admin/_dashboard/payroll-management/data-summary/kpi/index'
import { Route as PrivateAdminDashboardPayrollManagementDataSummaryAttendanceDataIndexRouteImport } from './routes/_private/admin/_dashboard/payroll-management/data-summary/attendance-data/index'

const PrivateAdminDashboardDashboardLazyRouteImport = createFileRoute(
  '/_private/admin/_dashboard/dashboard',
)()

const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/unauthenticated',
  path: '/unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/authenticated',
  path: '/authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateLogoutRoute = PrivateLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => PrivateRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const PrivateAdminIndexRoute = PrivateAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => PrivateRoute,
} as any)
const AuthTimekeepingShiftSchedulingIndexRoute =
  AuthTimekeepingShiftSchedulingIndexRouteImport.update({
    id: '/timekeeping-shift-scheduling/',
    path: '/timekeeping-shift-scheduling/',
    getParentRoute: () => AuthRoute,
  } as any)
const PrivateAdminDashboardRoute = PrivateAdminDashboardRouteImport.update({
  id: '/admin/_dashboard',
  path: '/admin',
  getParentRoute: () => PrivateRoute,
} as any)
const AuthTimekeepingShiftSchedulingTimekeepingManagementIndexRoute =
  AuthTimekeepingShiftSchedulingTimekeepingManagementIndexRouteImport.update({
    id: '/timekeeping-shift-scheduling/timekeeping-management/',
    path: '/timekeeping-shift-scheduling/timekeeping-management/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthTimekeepingShiftSchedulingShiftManagementIndexRoute =
  AuthTimekeepingShiftSchedulingShiftManagementIndexRouteImport.update({
    id: '/timekeeping-shift-scheduling/shift-management/',
    path: '/timekeeping-shift-scheduling/shift-management/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthTimekeepingShiftSchedulingExplanationManagementIndexRoute =
  AuthTimekeepingShiftSchedulingExplanationManagementIndexRouteImport.update({
    id: '/timekeeping-shift-scheduling/explanation-management/',
    path: '/timekeeping-shift-scheduling/explanation-management/',
    getParentRoute: () => AuthRoute,
  } as any)
const PrivateAdminDashboardDashboardLazyRoute =
  PrivateAdminDashboardDashboardLazyRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => PrivateAdminDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_private/admin/_dashboard/dashboard.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateAdminDashboardTimekeepingShiftSchedulingIndexRoute =
  PrivateAdminDashboardTimekeepingShiftSchedulingIndexRouteImport.update({
    id: '/timekeeping-shift-scheduling/',
    path: '/timekeeping-shift-scheduling/',
    getParentRoute: () => PrivateAdminDashboardRoute,
  } as any)
const PrivateAdminDashboardStaffManagementIndexRoute =
  PrivateAdminDashboardStaffManagementIndexRouteImport.update({
    id: '/staff-management/',
    path: '/staff-management/',
    getParentRoute: () => PrivateAdminDashboardRoute,
  } as any)
const PrivateAdminDashboardRecruitmentManagementIndexRoute =
  PrivateAdminDashboardRecruitmentManagementIndexRouteImport.update({
    id: '/recruitment-management/',
    path: '/recruitment-management/',
    getParentRoute: () => PrivateAdminDashboardRoute,
  } as any)
const PrivateAdminDashboardPayrollManagementIndexRoute =
  PrivateAdminDashboardPayrollManagementIndexRouteImport.update({
    id: '/payroll-management/',
    path: '/payroll-management/',
    getParentRoute: () => PrivateAdminDashboardRoute,
  } as any)
const PrivateAdminDashboardOtherRequestsManagementIndexRoute =
  PrivateAdminDashboardOtherRequestsManagementIndexRouteImport.update({
    id: '/other-requests-management/',
    path: '/other-requests-management/',
    getParentRoute: () => PrivateAdminDashboardRoute,
  } as any)
const PrivateAdminDashboardManagementReportIndexRoute =
  PrivateAdminDashboardManagementReportIndexRouteImport.update({
    id: '/management-report/',
    path: '/management-report/',
    getParentRoute: () => PrivateAdminDashboardRoute,
  } as any)
const PrivateAdminDashboardLeaveManagementIndexRoute =
  PrivateAdminDashboardLeaveManagementIndexRouteImport.update({
    id: '/leave-management/',
    path: '/leave-management/',
    getParentRoute: () => PrivateAdminDashboardRoute,
  } as any)
const PrivateAdminDashboardContractManagementIndexRoute =
  PrivateAdminDashboardContractManagementIndexRouteImport.update({
    id: '/contract-management/',
    path: '/contract-management/',
    getParentRoute: () => PrivateAdminDashboardRoute,
  } as any)
const PrivateAdminDashboardStaffManagementTypeRoute =
  PrivateAdminDashboardStaffManagementTypeRouteImport.update({
    id: '/staff-management/$type',
    path: '/staff-management/$type',
    getParentRoute: () => PrivateAdminDashboardRoute,
  } as any)
const PrivateAdminDashboardPayrollManagementSalaryHistoryRoute =
  PrivateAdminDashboardPayrollManagementSalaryHistoryRouteImport.update({
    id: '/payroll-management/salary-history',
    path: '/payroll-management/salary-history',
    getParentRoute: () => PrivateAdminDashboardRoute,
  } as any)
const PrivateAdminDashboardPayrollManagementPayslipFeedbackRoute =
  PrivateAdminDashboardPayrollManagementPayslipFeedbackRouteImport.update({
    id: '/payroll-management/payslip-feedback',
    path: '/payroll-management/payslip-feedback',
    getParentRoute: () => PrivateAdminDashboardRoute,
  } as any)
const PrivateAdminDashboardPayrollManagementPayrollCalculationRoute =
  PrivateAdminDashboardPayrollManagementPayrollCalculationRouteImport.update({
    id: '/payroll-management/payroll-calculation',
    path: '/payroll-management/payroll-calculation',
    getParentRoute: () => PrivateAdminDashboardRoute,
  } as any)
const PrivateAdminDashboardOtherRequestsManagementTrainingRegistrationRanagementRoute =
  PrivateAdminDashboardOtherRequestsManagementTrainingRegistrationRanagementRouteImport.update(
    {
      id: '/other-requests-management/training-registration-ranagement',
      path: '/other-requests-management/training-registration-ranagement',
      getParentRoute: () => PrivateAdminDashboardRoute,
    } as any,
  )
const PrivateAdminDashboardOtherRequestsManagementRemoteWorkManagementRoute =
  PrivateAdminDashboardOtherRequestsManagementRemoteWorkManagementRouteImport.update(
    {
      id: '/other-requests-management/remote-work-management',
      path: '/other-requests-management/remote-work-management',
      getParentRoute: () => PrivateAdminDashboardRoute,
    } as any,
  )
const PrivateAdminDashboardOtherRequestsManagementOvertimeManagementRoute =
  PrivateAdminDashboardOtherRequestsManagementOvertimeManagementRouteImport.update(
    {
      id: '/other-requests-management/overtime-management',
      path: '/other-requests-management/overtime-management',
      getParentRoute: () => PrivateAdminDashboardRoute,
    } as any,
  )
const PrivateAdminDashboardOtherRequestsManagementBusinessTripManagementRoute =
  PrivateAdminDashboardOtherRequestsManagementBusinessTripManagementRouteImport.update(
    {
      id: '/other-requests-management/business-trip-management',
      path: '/other-requests-management/business-trip-management',
      getParentRoute: () => PrivateAdminDashboardRoute,
    } as any,
  )
const PrivateAdminDashboardLeaveManagementLeaveRequestManagementRoute =
  PrivateAdminDashboardLeaveManagementLeaveRequestManagementRouteImport.update({
    id: '/leave-management/leave-request-management',
    path: '/leave-management/leave-request-management',
    getParentRoute: () => PrivateAdminDashboardRoute,
  } as any)
const PrivateAdminDashboardPayrollManagementDataSummaryRouteRoute =
  PrivateAdminDashboardPayrollManagementDataSummaryRouteRouteImport.update({
    id: '/payroll-management/data-summary',
    path: '/payroll-management/data-summary',
    getParentRoute: () => PrivateAdminDashboardRoute,
  } as any)
const PrivateAdminDashboardTimekeepingShiftSchedulingTimekeepingManagementIndexRoute =
  PrivateAdminDashboardTimekeepingShiftSchedulingTimekeepingManagementIndexRouteImport.update(
    {
      id: '/timekeeping-shift-scheduling/timekeeping-management/',
      path: '/timekeeping-shift-scheduling/timekeeping-management/',
      getParentRoute: () => PrivateAdminDashboardRoute,
    } as any,
  )
const PrivateAdminDashboardTimekeepingShiftSchedulingShiftManagementIndexRoute =
  PrivateAdminDashboardTimekeepingShiftSchedulingShiftManagementIndexRouteImport.update(
    {
      id: '/timekeeping-shift-scheduling/shift-management/',
      path: '/timekeeping-shift-scheduling/shift-management/',
      getParentRoute: () => PrivateAdminDashboardRoute,
    } as any,
  )
const PrivateAdminDashboardTimekeepingShiftSchedulingExplanationManagementIndexRoute =
  PrivateAdminDashboardTimekeepingShiftSchedulingExplanationManagementIndexRouteImport.update(
    {
      id: '/timekeeping-shift-scheduling/explanation-management/',
      path: '/timekeeping-shift-scheduling/explanation-management/',
      getParentRoute: () => PrivateAdminDashboardRoute,
    } as any,
  )
const PrivateAdminDashboardPayrollManagementDataSummaryIndexRoute =
  PrivateAdminDashboardPayrollManagementDataSummaryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      PrivateAdminDashboardPayrollManagementDataSummaryRouteRoute,
  } as any)
const PrivateAdminDashboardStaffManagementDetailIdRoute =
  PrivateAdminDashboardStaffManagementDetailIdRouteImport.update({
    id: '/staff-management/detail/$id',
    path: '/staff-management/detail/$id',
    getParentRoute: () => PrivateAdminDashboardRoute,
  } as any)
const PrivateAdminDashboardPayrollManagementDataSummarySummaryFinalizeIndexRoute =
  PrivateAdminDashboardPayrollManagementDataSummarySummaryFinalizeIndexRouteImport.update(
    {
      id: '/summary-finalize/',
      path: '/summary-finalize/',
      getParentRoute: () =>
        PrivateAdminDashboardPayrollManagementDataSummaryRouteRoute,
    } as any,
  )
const PrivateAdminDashboardPayrollManagementDataSummaryRevenueIndexRoute =
  PrivateAdminDashboardPayrollManagementDataSummaryRevenueIndexRouteImport.update(
    {
      id: '/revenue/',
      path: '/revenue/',
      getParentRoute: () =>
        PrivateAdminDashboardPayrollManagementDataSummaryRouteRoute,
    } as any,
  )
const PrivateAdminDashboardPayrollManagementDataSummaryOtherIncomeIndexRoute =
  PrivateAdminDashboardPayrollManagementDataSummaryOtherIncomeIndexRouteImport.update(
    {
      id: '/other-income/',
      path: '/other-income/',
      getParentRoute: () =>
        PrivateAdminDashboardPayrollManagementDataSummaryRouteRoute,
    } as any,
  )
const PrivateAdminDashboardPayrollManagementDataSummaryKpiIndexRoute =
  PrivateAdminDashboardPayrollManagementDataSummaryKpiIndexRouteImport.update({
    id: '/kpi/',
    path: '/kpi/',
    getParentRoute: () =>
      PrivateAdminDashboardPayrollManagementDataSummaryRouteRoute,
  } as any)
const PrivateAdminDashboardPayrollManagementDataSummaryAttendanceDataIndexRoute =
  PrivateAdminDashboardPayrollManagementDataSummaryAttendanceDataIndexRouteImport.update(
    {
      id: '/attendance-data/',
      path: '/attendance-data/',
      getParentRoute: () =>
        PrivateAdminDashboardPayrollManagementDataSummaryRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authenticated': typeof AuthenticatedRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/login': typeof AuthLoginRoute
  '/logout': typeof PrivateLogoutRoute
  '/admin': typeof PrivateAdminDashboardRouteWithChildren
  '/timekeeping-shift-scheduling/': typeof AuthTimekeepingShiftSchedulingIndexRoute
  '/admin/': typeof PrivateAdminIndexRoute
  '/admin/dashboard': typeof PrivateAdminDashboardDashboardLazyRoute
  '/timekeeping-shift-scheduling/explanation-management/': typeof AuthTimekeepingShiftSchedulingExplanationManagementIndexRoute
  '/timekeeping-shift-scheduling/shift-management/': typeof AuthTimekeepingShiftSchedulingShiftManagementIndexRoute
  '/timekeeping-shift-scheduling/timekeeping-management/': typeof AuthTimekeepingShiftSchedulingTimekeepingManagementIndexRoute
  '/admin/payroll-management/data-summary': typeof PrivateAdminDashboardPayrollManagementDataSummaryRouteRouteWithChildren
  '/admin/leave-management/leave-request-management': typeof PrivateAdminDashboardLeaveManagementLeaveRequestManagementRoute
  '/admin/other-requests-management/business-trip-management': typeof PrivateAdminDashboardOtherRequestsManagementBusinessTripManagementRoute
  '/admin/other-requests-management/overtime-management': typeof PrivateAdminDashboardOtherRequestsManagementOvertimeManagementRoute
  '/admin/other-requests-management/remote-work-management': typeof PrivateAdminDashboardOtherRequestsManagementRemoteWorkManagementRoute
  '/admin/other-requests-management/training-registration-ranagement': typeof PrivateAdminDashboardOtherRequestsManagementTrainingRegistrationRanagementRoute
  '/admin/payroll-management/payroll-calculation': typeof PrivateAdminDashboardPayrollManagementPayrollCalculationRoute
  '/admin/payroll-management/payslip-feedback': typeof PrivateAdminDashboardPayrollManagementPayslipFeedbackRoute
  '/admin/payroll-management/salary-history': typeof PrivateAdminDashboardPayrollManagementSalaryHistoryRoute
  '/admin/staff-management/$type': typeof PrivateAdminDashboardStaffManagementTypeRoute
  '/admin/contract-management/': typeof PrivateAdminDashboardContractManagementIndexRoute
  '/admin/leave-management/': typeof PrivateAdminDashboardLeaveManagementIndexRoute
  '/admin/management-report/': typeof PrivateAdminDashboardManagementReportIndexRoute
  '/admin/other-requests-management/': typeof PrivateAdminDashboardOtherRequestsManagementIndexRoute
  '/admin/payroll-management/': typeof PrivateAdminDashboardPayrollManagementIndexRoute
  '/admin/recruitment-management/': typeof PrivateAdminDashboardRecruitmentManagementIndexRoute
  '/admin/staff-management/': typeof PrivateAdminDashboardStaffManagementIndexRoute
  '/admin/timekeeping-shift-scheduling/': typeof PrivateAdminDashboardTimekeepingShiftSchedulingIndexRoute
  '/admin/staff-management/detail/$id': typeof PrivateAdminDashboardStaffManagementDetailIdRoute
  '/admin/payroll-management/data-summary/': typeof PrivateAdminDashboardPayrollManagementDataSummaryIndexRoute
  '/admin/timekeeping-shift-scheduling/explanation-management/': typeof PrivateAdminDashboardTimekeepingShiftSchedulingExplanationManagementIndexRoute
  '/admin/timekeeping-shift-scheduling/shift-management/': typeof PrivateAdminDashboardTimekeepingShiftSchedulingShiftManagementIndexRoute
  '/admin/timekeeping-shift-scheduling/timekeeping-management/': typeof PrivateAdminDashboardTimekeepingShiftSchedulingTimekeepingManagementIndexRoute
  '/admin/payroll-management/data-summary/attendance-data/': typeof PrivateAdminDashboardPayrollManagementDataSummaryAttendanceDataIndexRoute
  '/admin/payroll-management/data-summary/kpi/': typeof PrivateAdminDashboardPayrollManagementDataSummaryKpiIndexRoute
  '/admin/payroll-management/data-summary/other-income/': typeof PrivateAdminDashboardPayrollManagementDataSummaryOtherIncomeIndexRoute
  '/admin/payroll-management/data-summary/revenue/': typeof PrivateAdminDashboardPayrollManagementDataSummaryRevenueIndexRoute
  '/admin/payroll-management/data-summary/summary-finalize/': typeof PrivateAdminDashboardPayrollManagementDataSummarySummaryFinalizeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authenticated': typeof AuthenticatedRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/login': typeof AuthLoginRoute
  '/logout': typeof PrivateLogoutRoute
  '/admin': typeof PrivateAdminIndexRoute
  '/timekeeping-shift-scheduling': typeof AuthTimekeepingShiftSchedulingIndexRoute
  '/admin/dashboard': typeof PrivateAdminDashboardDashboardLazyRoute
  '/timekeeping-shift-scheduling/explanation-management': typeof AuthTimekeepingShiftSchedulingExplanationManagementIndexRoute
  '/timekeeping-shift-scheduling/shift-management': typeof AuthTimekeepingShiftSchedulingShiftManagementIndexRoute
  '/timekeeping-shift-scheduling/timekeeping-management': typeof AuthTimekeepingShiftSchedulingTimekeepingManagementIndexRoute
  '/admin/leave-management/leave-request-management': typeof PrivateAdminDashboardLeaveManagementLeaveRequestManagementRoute
  '/admin/other-requests-management/business-trip-management': typeof PrivateAdminDashboardOtherRequestsManagementBusinessTripManagementRoute
  '/admin/other-requests-management/overtime-management': typeof PrivateAdminDashboardOtherRequestsManagementOvertimeManagementRoute
  '/admin/other-requests-management/remote-work-management': typeof PrivateAdminDashboardOtherRequestsManagementRemoteWorkManagementRoute
  '/admin/other-requests-management/training-registration-ranagement': typeof PrivateAdminDashboardOtherRequestsManagementTrainingRegistrationRanagementRoute
  '/admin/payroll-management/payroll-calculation': typeof PrivateAdminDashboardPayrollManagementPayrollCalculationRoute
  '/admin/payroll-management/payslip-feedback': typeof PrivateAdminDashboardPayrollManagementPayslipFeedbackRoute
  '/admin/payroll-management/salary-history': typeof PrivateAdminDashboardPayrollManagementSalaryHistoryRoute
  '/admin/staff-management/$type': typeof PrivateAdminDashboardStaffManagementTypeRoute
  '/admin/contract-management': typeof PrivateAdminDashboardContractManagementIndexRoute
  '/admin/leave-management': typeof PrivateAdminDashboardLeaveManagementIndexRoute
  '/admin/management-report': typeof PrivateAdminDashboardManagementReportIndexRoute
  '/admin/other-requests-management': typeof PrivateAdminDashboardOtherRequestsManagementIndexRoute
  '/admin/payroll-management': typeof PrivateAdminDashboardPayrollManagementIndexRoute
  '/admin/recruitment-management': typeof PrivateAdminDashboardRecruitmentManagementIndexRoute
  '/admin/staff-management': typeof PrivateAdminDashboardStaffManagementIndexRoute
  '/admin/timekeeping-shift-scheduling': typeof PrivateAdminDashboardTimekeepingShiftSchedulingIndexRoute
  '/admin/staff-management/detail/$id': typeof PrivateAdminDashboardStaffManagementDetailIdRoute
  '/admin/payroll-management/data-summary': typeof PrivateAdminDashboardPayrollManagementDataSummaryIndexRoute
  '/admin/timekeeping-shift-scheduling/explanation-management': typeof PrivateAdminDashboardTimekeepingShiftSchedulingExplanationManagementIndexRoute
  '/admin/timekeeping-shift-scheduling/shift-management': typeof PrivateAdminDashboardTimekeepingShiftSchedulingShiftManagementIndexRoute
  '/admin/timekeeping-shift-scheduling/timekeeping-management': typeof PrivateAdminDashboardTimekeepingShiftSchedulingTimekeepingManagementIndexRoute
  '/admin/payroll-management/data-summary/attendance-data': typeof PrivateAdminDashboardPayrollManagementDataSummaryAttendanceDataIndexRoute
  '/admin/payroll-management/data-summary/kpi': typeof PrivateAdminDashboardPayrollManagementDataSummaryKpiIndexRoute
  '/admin/payroll-management/data-summary/other-income': typeof PrivateAdminDashboardPayrollManagementDataSummaryOtherIncomeIndexRoute
  '/admin/payroll-management/data-summary/revenue': typeof PrivateAdminDashboardPayrollManagementDataSummaryRevenueIndexRoute
  '/admin/payroll-management/data-summary/summary-finalize': typeof PrivateAdminDashboardPayrollManagementDataSummarySummaryFinalizeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_private': typeof PrivateRouteWithChildren
  '/authenticated': typeof AuthenticatedRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_private/logout': typeof PrivateLogoutRoute
  '/_private/admin/_dashboard': typeof PrivateAdminDashboardRouteWithChildren
  '/_auth/timekeeping-shift-scheduling/': typeof AuthTimekeepingShiftSchedulingIndexRoute
  '/_private/admin/': typeof PrivateAdminIndexRoute
  '/_private/admin/_dashboard/dashboard': typeof PrivateAdminDashboardDashboardLazyRoute
  '/_auth/timekeeping-shift-scheduling/explanation-management/': typeof AuthTimekeepingShiftSchedulingExplanationManagementIndexRoute
  '/_auth/timekeeping-shift-scheduling/shift-management/': typeof AuthTimekeepingShiftSchedulingShiftManagementIndexRoute
  '/_auth/timekeeping-shift-scheduling/timekeeping-management/': typeof AuthTimekeepingShiftSchedulingTimekeepingManagementIndexRoute
  '/_private/admin/_dashboard/payroll-management/data-summary': typeof PrivateAdminDashboardPayrollManagementDataSummaryRouteRouteWithChildren
  '/_private/admin/_dashboard/leave-management/leave-request-management': typeof PrivateAdminDashboardLeaveManagementLeaveRequestManagementRoute
  '/_private/admin/_dashboard/other-requests-management/business-trip-management': typeof PrivateAdminDashboardOtherRequestsManagementBusinessTripManagementRoute
  '/_private/admin/_dashboard/other-requests-management/overtime-management': typeof PrivateAdminDashboardOtherRequestsManagementOvertimeManagementRoute
  '/_private/admin/_dashboard/other-requests-management/remote-work-management': typeof PrivateAdminDashboardOtherRequestsManagementRemoteWorkManagementRoute
  '/_private/admin/_dashboard/other-requests-management/training-registration-ranagement': typeof PrivateAdminDashboardOtherRequestsManagementTrainingRegistrationRanagementRoute
  '/_private/admin/_dashboard/payroll-management/payroll-calculation': typeof PrivateAdminDashboardPayrollManagementPayrollCalculationRoute
  '/_private/admin/_dashboard/payroll-management/payslip-feedback': typeof PrivateAdminDashboardPayrollManagementPayslipFeedbackRoute
  '/_private/admin/_dashboard/payroll-management/salary-history': typeof PrivateAdminDashboardPayrollManagementSalaryHistoryRoute
  '/_private/admin/_dashboard/staff-management/$type': typeof PrivateAdminDashboardStaffManagementTypeRoute
  '/_private/admin/_dashboard/contract-management/': typeof PrivateAdminDashboardContractManagementIndexRoute
  '/_private/admin/_dashboard/leave-management/': typeof PrivateAdminDashboardLeaveManagementIndexRoute
  '/_private/admin/_dashboard/management-report/': typeof PrivateAdminDashboardManagementReportIndexRoute
  '/_private/admin/_dashboard/other-requests-management/': typeof PrivateAdminDashboardOtherRequestsManagementIndexRoute
  '/_private/admin/_dashboard/payroll-management/': typeof PrivateAdminDashboardPayrollManagementIndexRoute
  '/_private/admin/_dashboard/recruitment-management/': typeof PrivateAdminDashboardRecruitmentManagementIndexRoute
  '/_private/admin/_dashboard/staff-management/': typeof PrivateAdminDashboardStaffManagementIndexRoute
  '/_private/admin/_dashboard/timekeeping-shift-scheduling/': typeof PrivateAdminDashboardTimekeepingShiftSchedulingIndexRoute
  '/_private/admin/_dashboard/staff-management/detail/$id': typeof PrivateAdminDashboardStaffManagementDetailIdRoute
  '/_private/admin/_dashboard/payroll-management/data-summary/': typeof PrivateAdminDashboardPayrollManagementDataSummaryIndexRoute
  '/_private/admin/_dashboard/timekeeping-shift-scheduling/explanation-management/': typeof PrivateAdminDashboardTimekeepingShiftSchedulingExplanationManagementIndexRoute
  '/_private/admin/_dashboard/timekeeping-shift-scheduling/shift-management/': typeof PrivateAdminDashboardTimekeepingShiftSchedulingShiftManagementIndexRoute
  '/_private/admin/_dashboard/timekeeping-shift-scheduling/timekeeping-management/': typeof PrivateAdminDashboardTimekeepingShiftSchedulingTimekeepingManagementIndexRoute
  '/_private/admin/_dashboard/payroll-management/data-summary/attendance-data/': typeof PrivateAdminDashboardPayrollManagementDataSummaryAttendanceDataIndexRoute
  '/_private/admin/_dashboard/payroll-management/data-summary/kpi/': typeof PrivateAdminDashboardPayrollManagementDataSummaryKpiIndexRoute
  '/_private/admin/_dashboard/payroll-management/data-summary/other-income/': typeof PrivateAdminDashboardPayrollManagementDataSummaryOtherIncomeIndexRoute
  '/_private/admin/_dashboard/payroll-management/data-summary/revenue/': typeof PrivateAdminDashboardPayrollManagementDataSummaryRevenueIndexRoute
  '/_private/admin/_dashboard/payroll-management/data-summary/summary-finalize/': typeof PrivateAdminDashboardPayrollManagementDataSummarySummaryFinalizeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authenticated'
    | '/unauthenticated'
    | '/login'
    | '/logout'
    | '/admin'
    | '/timekeeping-shift-scheduling/'
    | '/admin/'
    | '/admin/dashboard'
    | '/timekeeping-shift-scheduling/explanation-management/'
    | '/timekeeping-shift-scheduling/shift-management/'
    | '/timekeeping-shift-scheduling/timekeeping-management/'
    | '/admin/payroll-management/data-summary'
    | '/admin/leave-management/leave-request-management'
    | '/admin/other-requests-management/business-trip-management'
    | '/admin/other-requests-management/overtime-management'
    | '/admin/other-requests-management/remote-work-management'
    | '/admin/other-requests-management/training-registration-ranagement'
    | '/admin/payroll-management/payroll-calculation'
    | '/admin/payroll-management/payslip-feedback'
    | '/admin/payroll-management/salary-history'
    | '/admin/staff-management/$type'
    | '/admin/contract-management/'
    | '/admin/leave-management/'
    | '/admin/management-report/'
    | '/admin/other-requests-management/'
    | '/admin/payroll-management/'
    | '/admin/recruitment-management/'
    | '/admin/staff-management/'
    | '/admin/timekeeping-shift-scheduling/'
    | '/admin/staff-management/detail/$id'
    | '/admin/payroll-management/data-summary/'
    | '/admin/timekeeping-shift-scheduling/explanation-management/'
    | '/admin/timekeeping-shift-scheduling/shift-management/'
    | '/admin/timekeeping-shift-scheduling/timekeeping-management/'
    | '/admin/payroll-management/data-summary/attendance-data/'
    | '/admin/payroll-management/data-summary/kpi/'
    | '/admin/payroll-management/data-summary/other-income/'
    | '/admin/payroll-management/data-summary/revenue/'
    | '/admin/payroll-management/data-summary/summary-finalize/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authenticated'
    | '/unauthenticated'
    | '/login'
    | '/logout'
    | '/admin'
    | '/timekeeping-shift-scheduling'
    | '/admin/dashboard'
    | '/timekeeping-shift-scheduling/explanation-management'
    | '/timekeeping-shift-scheduling/shift-management'
    | '/timekeeping-shift-scheduling/timekeeping-management'
    | '/admin/leave-management/leave-request-management'
    | '/admin/other-requests-management/business-trip-management'
    | '/admin/other-requests-management/overtime-management'
    | '/admin/other-requests-management/remote-work-management'
    | '/admin/other-requests-management/training-registration-ranagement'
    | '/admin/payroll-management/payroll-calculation'
    | '/admin/payroll-management/payslip-feedback'
    | '/admin/payroll-management/salary-history'
    | '/admin/staff-management/$type'
    | '/admin/contract-management'
    | '/admin/leave-management'
    | '/admin/management-report'
    | '/admin/other-requests-management'
    | '/admin/payroll-management'
    | '/admin/recruitment-management'
    | '/admin/staff-management'
    | '/admin/timekeeping-shift-scheduling'
    | '/admin/staff-management/detail/$id'
    | '/admin/payroll-management/data-summary'
    | '/admin/timekeeping-shift-scheduling/explanation-management'
    | '/admin/timekeeping-shift-scheduling/shift-management'
    | '/admin/timekeeping-shift-scheduling/timekeeping-management'
    | '/admin/payroll-management/data-summary/attendance-data'
    | '/admin/payroll-management/data-summary/kpi'
    | '/admin/payroll-management/data-summary/other-income'
    | '/admin/payroll-management/data-summary/revenue'
    | '/admin/payroll-management/data-summary/summary-finalize'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_private'
    | '/authenticated'
    | '/unauthenticated'
    | '/_auth/login'
    | '/_private/logout'
    | '/_private/admin/_dashboard'
    | '/_auth/timekeeping-shift-scheduling/'
    | '/_private/admin/'
    | '/_private/admin/_dashboard/dashboard'
    | '/_auth/timekeeping-shift-scheduling/explanation-management/'
    | '/_auth/timekeeping-shift-scheduling/shift-management/'
    | '/_auth/timekeeping-shift-scheduling/timekeeping-management/'
    | '/_private/admin/_dashboard/payroll-management/data-summary'
    | '/_private/admin/_dashboard/leave-management/leave-request-management'
    | '/_private/admin/_dashboard/other-requests-management/business-trip-management'
    | '/_private/admin/_dashboard/other-requests-management/overtime-management'
    | '/_private/admin/_dashboard/other-requests-management/remote-work-management'
    | '/_private/admin/_dashboard/other-requests-management/training-registration-ranagement'
    | '/_private/admin/_dashboard/payroll-management/payroll-calculation'
    | '/_private/admin/_dashboard/payroll-management/payslip-feedback'
    | '/_private/admin/_dashboard/payroll-management/salary-history'
    | '/_private/admin/_dashboard/staff-management/$type'
    | '/_private/admin/_dashboard/contract-management/'
    | '/_private/admin/_dashboard/leave-management/'
    | '/_private/admin/_dashboard/management-report/'
    | '/_private/admin/_dashboard/other-requests-management/'
    | '/_private/admin/_dashboard/payroll-management/'
    | '/_private/admin/_dashboard/recruitment-management/'
    | '/_private/admin/_dashboard/staff-management/'
    | '/_private/admin/_dashboard/timekeeping-shift-scheduling/'
    | '/_private/admin/_dashboard/staff-management/detail/$id'
    | '/_private/admin/_dashboard/payroll-management/data-summary/'
    | '/_private/admin/_dashboard/timekeeping-shift-scheduling/explanation-management/'
    | '/_private/admin/_dashboard/timekeeping-shift-scheduling/shift-management/'
    | '/_private/admin/_dashboard/timekeeping-shift-scheduling/timekeeping-management/'
    | '/_private/admin/_dashboard/payroll-management/data-summary/attendance-data/'
    | '/_private/admin/_dashboard/payroll-management/data-summary/kpi/'
    | '/_private/admin/_dashboard/payroll-management/data-summary/other-income/'
    | '/_private/admin/_dashboard/payroll-management/data-summary/revenue/'
    | '/_private/admin/_dashboard/payroll-management/data-summary/summary-finalize/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  PrivateRoute: typeof PrivateRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRoute
  UnauthenticatedRoute: typeof UnauthenticatedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthenticated': {
      id: '/unauthenticated'
      path: '/unauthenticated'
      fullPath: '/unauthenticated'
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticated': {
      id: '/authenticated'
      path: '/authenticated'
      fullPath: '/authenticated'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/logout': {
      id: '/_private/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof PrivateLogoutRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_private/admin/': {
      id: '/_private/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof PrivateAdminIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_auth/timekeeping-shift-scheduling/': {
      id: '/_auth/timekeeping-shift-scheduling/'
      path: '/timekeeping-shift-scheduling'
      fullPath: '/timekeeping-shift-scheduling/'
      preLoaderRoute: typeof AuthTimekeepingShiftSchedulingIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_private/admin/_dashboard': {
      id: '/_private/admin/_dashboard'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof PrivateAdminDashboardRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_auth/timekeeping-shift-scheduling/timekeeping-management/': {
      id: '/_auth/timekeeping-shift-scheduling/timekeeping-management/'
      path: '/timekeeping-shift-scheduling/timekeeping-management'
      fullPath: '/timekeeping-shift-scheduling/timekeeping-management/'
      preLoaderRoute: typeof AuthTimekeepingShiftSchedulingTimekeepingManagementIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/timekeeping-shift-scheduling/shift-management/': {
      id: '/_auth/timekeeping-shift-scheduling/shift-management/'
      path: '/timekeeping-shift-scheduling/shift-management'
      fullPath: '/timekeeping-shift-scheduling/shift-management/'
      preLoaderRoute: typeof AuthTimekeepingShiftSchedulingShiftManagementIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/timekeeping-shift-scheduling/explanation-management/': {
      id: '/_auth/timekeeping-shift-scheduling/explanation-management/'
      path: '/timekeeping-shift-scheduling/explanation-management'
      fullPath: '/timekeeping-shift-scheduling/explanation-management/'
      preLoaderRoute: typeof AuthTimekeepingShiftSchedulingExplanationManagementIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_private/admin/_dashboard/dashboard': {
      id: '/_private/admin/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof PrivateAdminDashboardDashboardLazyRouteImport
      parentRoute: typeof PrivateAdminDashboardRoute
    }
    '/_private/admin/_dashboard/timekeeping-shift-scheduling/': {
      id: '/_private/admin/_dashboard/timekeeping-shift-scheduling/'
      path: '/timekeeping-shift-scheduling'
      fullPath: '/admin/timekeeping-shift-scheduling/'
      preLoaderRoute: typeof PrivateAdminDashboardTimekeepingShiftSchedulingIndexRouteImport
      parentRoute: typeof PrivateAdminDashboardRoute
    }
    '/_private/admin/_dashboard/staff-management/': {
      id: '/_private/admin/_dashboard/staff-management/'
      path: '/staff-management'
      fullPath: '/admin/staff-management/'
      preLoaderRoute: typeof PrivateAdminDashboardStaffManagementIndexRouteImport
      parentRoute: typeof PrivateAdminDashboardRoute
    }
    '/_private/admin/_dashboard/recruitment-management/': {
      id: '/_private/admin/_dashboard/recruitment-management/'
      path: '/recruitment-management'
      fullPath: '/admin/recruitment-management/'
      preLoaderRoute: typeof PrivateAdminDashboardRecruitmentManagementIndexRouteImport
      parentRoute: typeof PrivateAdminDashboardRoute
    }
    '/_private/admin/_dashboard/payroll-management/': {
      id: '/_private/admin/_dashboard/payroll-management/'
      path: '/payroll-management'
      fullPath: '/admin/payroll-management/'
      preLoaderRoute: typeof PrivateAdminDashboardPayrollManagementIndexRouteImport
      parentRoute: typeof PrivateAdminDashboardRoute
    }
    '/_private/admin/_dashboard/other-requests-management/': {
      id: '/_private/admin/_dashboard/other-requests-management/'
      path: '/other-requests-management'
      fullPath: '/admin/other-requests-management/'
      preLoaderRoute: typeof PrivateAdminDashboardOtherRequestsManagementIndexRouteImport
      parentRoute: typeof PrivateAdminDashboardRoute
    }
    '/_private/admin/_dashboard/management-report/': {
      id: '/_private/admin/_dashboard/management-report/'
      path: '/management-report'
      fullPath: '/admin/management-report/'
      preLoaderRoute: typeof PrivateAdminDashboardManagementReportIndexRouteImport
      parentRoute: typeof PrivateAdminDashboardRoute
    }
    '/_private/admin/_dashboard/leave-management/': {
      id: '/_private/admin/_dashboard/leave-management/'
      path: '/leave-management'
      fullPath: '/admin/leave-management/'
      preLoaderRoute: typeof PrivateAdminDashboardLeaveManagementIndexRouteImport
      parentRoute: typeof PrivateAdminDashboardRoute
    }
    '/_private/admin/_dashboard/contract-management/': {
      id: '/_private/admin/_dashboard/contract-management/'
      path: '/contract-management'
      fullPath: '/admin/contract-management/'
      preLoaderRoute: typeof PrivateAdminDashboardContractManagementIndexRouteImport
      parentRoute: typeof PrivateAdminDashboardRoute
    }
    '/_private/admin/_dashboard/staff-management/$type': {
      id: '/_private/admin/_dashboard/staff-management/$type'
      path: '/staff-management/$type'
      fullPath: '/admin/staff-management/$type'
      preLoaderRoute: typeof PrivateAdminDashboardStaffManagementTypeRouteImport
      parentRoute: typeof PrivateAdminDashboardRoute
    }
    '/_private/admin/_dashboard/payroll-management/salary-history': {
      id: '/_private/admin/_dashboard/payroll-management/salary-history'
      path: '/payroll-management/salary-history'
      fullPath: '/admin/payroll-management/salary-history'
      preLoaderRoute: typeof PrivateAdminDashboardPayrollManagementSalaryHistoryRouteImport
      parentRoute: typeof PrivateAdminDashboardRoute
    }
    '/_private/admin/_dashboard/payroll-management/payslip-feedback': {
      id: '/_private/admin/_dashboard/payroll-management/payslip-feedback'
      path: '/payroll-management/payslip-feedback'
      fullPath: '/admin/payroll-management/payslip-feedback'
      preLoaderRoute: typeof PrivateAdminDashboardPayrollManagementPayslipFeedbackRouteImport
      parentRoute: typeof PrivateAdminDashboardRoute
    }
    '/_private/admin/_dashboard/payroll-management/payroll-calculation': {
      id: '/_private/admin/_dashboard/payroll-management/payroll-calculation'
      path: '/payroll-management/payroll-calculation'
      fullPath: '/admin/payroll-management/payroll-calculation'
      preLoaderRoute: typeof PrivateAdminDashboardPayrollManagementPayrollCalculationRouteImport
      parentRoute: typeof PrivateAdminDashboardRoute
    }
    '/_private/admin/_dashboard/other-requests-management/training-registration-ranagement': {
      id: '/_private/admin/_dashboard/other-requests-management/training-registration-ranagement'
      path: '/other-requests-management/training-registration-ranagement'
      fullPath: '/admin/other-requests-management/training-registration-ranagement'
      preLoaderRoute: typeof PrivateAdminDashboardOtherRequestsManagementTrainingRegistrationRanagementRouteImport
      parentRoute: typeof PrivateAdminDashboardRoute
    }
    '/_private/admin/_dashboard/other-requests-management/remote-work-management': {
      id: '/_private/admin/_dashboard/other-requests-management/remote-work-management'
      path: '/other-requests-management/remote-work-management'
      fullPath: '/admin/other-requests-management/remote-work-management'
      preLoaderRoute: typeof PrivateAdminDashboardOtherRequestsManagementRemoteWorkManagementRouteImport
      parentRoute: typeof PrivateAdminDashboardRoute
    }
    '/_private/admin/_dashboard/other-requests-management/overtime-management': {
      id: '/_private/admin/_dashboard/other-requests-management/overtime-management'
      path: '/other-requests-management/overtime-management'
      fullPath: '/admin/other-requests-management/overtime-management'
      preLoaderRoute: typeof PrivateAdminDashboardOtherRequestsManagementOvertimeManagementRouteImport
      parentRoute: typeof PrivateAdminDashboardRoute
    }
    '/_private/admin/_dashboard/other-requests-management/business-trip-management': {
      id: '/_private/admin/_dashboard/other-requests-management/business-trip-management'
      path: '/other-requests-management/business-trip-management'
      fullPath: '/admin/other-requests-management/business-trip-management'
      preLoaderRoute: typeof PrivateAdminDashboardOtherRequestsManagementBusinessTripManagementRouteImport
      parentRoute: typeof PrivateAdminDashboardRoute
    }
    '/_private/admin/_dashboard/leave-management/leave-request-management': {
      id: '/_private/admin/_dashboard/leave-management/leave-request-management'
      path: '/leave-management/leave-request-management'
      fullPath: '/admin/leave-management/leave-request-management'
      preLoaderRoute: typeof PrivateAdminDashboardLeaveManagementLeaveRequestManagementRouteImport
      parentRoute: typeof PrivateAdminDashboardRoute
    }
    '/_private/admin/_dashboard/payroll-management/data-summary': {
      id: '/_private/admin/_dashboard/payroll-management/data-summary'
      path: '/payroll-management/data-summary'
      fullPath: '/admin/payroll-management/data-summary'
      preLoaderRoute: typeof PrivateAdminDashboardPayrollManagementDataSummaryRouteRouteImport
      parentRoute: typeof PrivateAdminDashboardRoute
    }
    '/_private/admin/_dashboard/timekeeping-shift-scheduling/timekeeping-management/': {
      id: '/_private/admin/_dashboard/timekeeping-shift-scheduling/timekeeping-management/'
      path: '/timekeeping-shift-scheduling/timekeeping-management'
      fullPath: '/admin/timekeeping-shift-scheduling/timekeeping-management/'
      preLoaderRoute: typeof PrivateAdminDashboardTimekeepingShiftSchedulingTimekeepingManagementIndexRouteImport
      parentRoute: typeof PrivateAdminDashboardRoute
    }
    '/_private/admin/_dashboard/timekeeping-shift-scheduling/shift-management/': {
      id: '/_private/admin/_dashboard/timekeeping-shift-scheduling/shift-management/'
      path: '/timekeeping-shift-scheduling/shift-management'
      fullPath: '/admin/timekeeping-shift-scheduling/shift-management/'
      preLoaderRoute: typeof PrivateAdminDashboardTimekeepingShiftSchedulingShiftManagementIndexRouteImport
      parentRoute: typeof PrivateAdminDashboardRoute
    }
    '/_private/admin/_dashboard/timekeeping-shift-scheduling/explanation-management/': {
      id: '/_private/admin/_dashboard/timekeeping-shift-scheduling/explanation-management/'
      path: '/timekeeping-shift-scheduling/explanation-management'
      fullPath: '/admin/timekeeping-shift-scheduling/explanation-management/'
      preLoaderRoute: typeof PrivateAdminDashboardTimekeepingShiftSchedulingExplanationManagementIndexRouteImport
      parentRoute: typeof PrivateAdminDashboardRoute
    }
    '/_private/admin/_dashboard/payroll-management/data-summary/': {
      id: '/_private/admin/_dashboard/payroll-management/data-summary/'
      path: '/'
      fullPath: '/admin/payroll-management/data-summary/'
      preLoaderRoute: typeof PrivateAdminDashboardPayrollManagementDataSummaryIndexRouteImport
      parentRoute: typeof PrivateAdminDashboardPayrollManagementDataSummaryRouteRoute
    }
    '/_private/admin/_dashboard/staff-management/detail/$id': {
      id: '/_private/admin/_dashboard/staff-management/detail/$id'
      path: '/staff-management/detail/$id'
      fullPath: '/admin/staff-management/detail/$id'
      preLoaderRoute: typeof PrivateAdminDashboardStaffManagementDetailIdRouteImport
      parentRoute: typeof PrivateAdminDashboardRoute
    }
    '/_private/admin/_dashboard/payroll-management/data-summary/summary-finalize/': {
      id: '/_private/admin/_dashboard/payroll-management/data-summary/summary-finalize/'
      path: '/summary-finalize'
      fullPath: '/admin/payroll-management/data-summary/summary-finalize/'
      preLoaderRoute: typeof PrivateAdminDashboardPayrollManagementDataSummarySummaryFinalizeIndexRouteImport
      parentRoute: typeof PrivateAdminDashboardPayrollManagementDataSummaryRouteRoute
    }
    '/_private/admin/_dashboard/payroll-management/data-summary/revenue/': {
      id: '/_private/admin/_dashboard/payroll-management/data-summary/revenue/'
      path: '/revenue'
      fullPath: '/admin/payroll-management/data-summary/revenue/'
      preLoaderRoute: typeof PrivateAdminDashboardPayrollManagementDataSummaryRevenueIndexRouteImport
      parentRoute: typeof PrivateAdminDashboardPayrollManagementDataSummaryRouteRoute
    }
    '/_private/admin/_dashboard/payroll-management/data-summary/other-income/': {
      id: '/_private/admin/_dashboard/payroll-management/data-summary/other-income/'
      path: '/other-income'
      fullPath: '/admin/payroll-management/data-summary/other-income/'
      preLoaderRoute: typeof PrivateAdminDashboardPayrollManagementDataSummaryOtherIncomeIndexRouteImport
      parentRoute: typeof PrivateAdminDashboardPayrollManagementDataSummaryRouteRoute
    }
    '/_private/admin/_dashboard/payroll-management/data-summary/kpi/': {
      id: '/_private/admin/_dashboard/payroll-management/data-summary/kpi/'
      path: '/kpi'
      fullPath: '/admin/payroll-management/data-summary/kpi/'
      preLoaderRoute: typeof PrivateAdminDashboardPayrollManagementDataSummaryKpiIndexRouteImport
      parentRoute: typeof PrivateAdminDashboardPayrollManagementDataSummaryRouteRoute
    }
    '/_private/admin/_dashboard/payroll-management/data-summary/attendance-data/': {
      id: '/_private/admin/_dashboard/payroll-management/data-summary/attendance-data/'
      path: '/attendance-data'
      fullPath: '/admin/payroll-management/data-summary/attendance-data/'
      preLoaderRoute: typeof PrivateAdminDashboardPayrollManagementDataSummaryAttendanceDataIndexRouteImport
      parentRoute: typeof PrivateAdminDashboardPayrollManagementDataSummaryRouteRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthTimekeepingShiftSchedulingIndexRoute: typeof AuthTimekeepingShiftSchedulingIndexRoute
  AuthTimekeepingShiftSchedulingExplanationManagementIndexRoute: typeof AuthTimekeepingShiftSchedulingExplanationManagementIndexRoute
  AuthTimekeepingShiftSchedulingShiftManagementIndexRoute: typeof AuthTimekeepingShiftSchedulingShiftManagementIndexRoute
  AuthTimekeepingShiftSchedulingTimekeepingManagementIndexRoute: typeof AuthTimekeepingShiftSchedulingTimekeepingManagementIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthTimekeepingShiftSchedulingIndexRoute:
    AuthTimekeepingShiftSchedulingIndexRoute,
  AuthTimekeepingShiftSchedulingExplanationManagementIndexRoute:
    AuthTimekeepingShiftSchedulingExplanationManagementIndexRoute,
  AuthTimekeepingShiftSchedulingShiftManagementIndexRoute:
    AuthTimekeepingShiftSchedulingShiftManagementIndexRoute,
  AuthTimekeepingShiftSchedulingTimekeepingManagementIndexRoute:
    AuthTimekeepingShiftSchedulingTimekeepingManagementIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PrivateAdminDashboardPayrollManagementDataSummaryRouteRouteChildren {
  PrivateAdminDashboardPayrollManagementDataSummaryIndexRoute: typeof PrivateAdminDashboardPayrollManagementDataSummaryIndexRoute
  PrivateAdminDashboardPayrollManagementDataSummaryAttendanceDataIndexRoute: typeof PrivateAdminDashboardPayrollManagementDataSummaryAttendanceDataIndexRoute
  PrivateAdminDashboardPayrollManagementDataSummaryKpiIndexRoute: typeof PrivateAdminDashboardPayrollManagementDataSummaryKpiIndexRoute
  PrivateAdminDashboardPayrollManagementDataSummaryOtherIncomeIndexRoute: typeof PrivateAdminDashboardPayrollManagementDataSummaryOtherIncomeIndexRoute
  PrivateAdminDashboardPayrollManagementDataSummaryRevenueIndexRoute: typeof PrivateAdminDashboardPayrollManagementDataSummaryRevenueIndexRoute
  PrivateAdminDashboardPayrollManagementDataSummarySummaryFinalizeIndexRoute: typeof PrivateAdminDashboardPayrollManagementDataSummarySummaryFinalizeIndexRoute
}

const PrivateAdminDashboardPayrollManagementDataSummaryRouteRouteChildren: PrivateAdminDashboardPayrollManagementDataSummaryRouteRouteChildren =
  {
    PrivateAdminDashboardPayrollManagementDataSummaryIndexRoute:
      PrivateAdminDashboardPayrollManagementDataSummaryIndexRoute,
    PrivateAdminDashboardPayrollManagementDataSummaryAttendanceDataIndexRoute:
      PrivateAdminDashboardPayrollManagementDataSummaryAttendanceDataIndexRoute,
    PrivateAdminDashboardPayrollManagementDataSummaryKpiIndexRoute:
      PrivateAdminDashboardPayrollManagementDataSummaryKpiIndexRoute,
    PrivateAdminDashboardPayrollManagementDataSummaryOtherIncomeIndexRoute:
      PrivateAdminDashboardPayrollManagementDataSummaryOtherIncomeIndexRoute,
    PrivateAdminDashboardPayrollManagementDataSummaryRevenueIndexRoute:
      PrivateAdminDashboardPayrollManagementDataSummaryRevenueIndexRoute,
    PrivateAdminDashboardPayrollManagementDataSummarySummaryFinalizeIndexRoute:
      PrivateAdminDashboardPayrollManagementDataSummarySummaryFinalizeIndexRoute,
  }

const PrivateAdminDashboardPayrollManagementDataSummaryRouteRouteWithChildren =
  PrivateAdminDashboardPayrollManagementDataSummaryRouteRoute._addFileChildren(
    PrivateAdminDashboardPayrollManagementDataSummaryRouteRouteChildren,
  )

interface PrivateAdminDashboardRouteChildren {
  PrivateAdminDashboardDashboardLazyRoute: typeof PrivateAdminDashboardDashboardLazyRoute
  PrivateAdminDashboardPayrollManagementDataSummaryRouteRoute: typeof PrivateAdminDashboardPayrollManagementDataSummaryRouteRouteWithChildren
  PrivateAdminDashboardLeaveManagementLeaveRequestManagementRoute: typeof PrivateAdminDashboardLeaveManagementLeaveRequestManagementRoute
  PrivateAdminDashboardOtherRequestsManagementBusinessTripManagementRoute: typeof PrivateAdminDashboardOtherRequestsManagementBusinessTripManagementRoute
  PrivateAdminDashboardOtherRequestsManagementOvertimeManagementRoute: typeof PrivateAdminDashboardOtherRequestsManagementOvertimeManagementRoute
  PrivateAdminDashboardOtherRequestsManagementRemoteWorkManagementRoute: typeof PrivateAdminDashboardOtherRequestsManagementRemoteWorkManagementRoute
  PrivateAdminDashboardOtherRequestsManagementTrainingRegistrationRanagementRoute: typeof PrivateAdminDashboardOtherRequestsManagementTrainingRegistrationRanagementRoute
  PrivateAdminDashboardPayrollManagementPayrollCalculationRoute: typeof PrivateAdminDashboardPayrollManagementPayrollCalculationRoute
  PrivateAdminDashboardPayrollManagementPayslipFeedbackRoute: typeof PrivateAdminDashboardPayrollManagementPayslipFeedbackRoute
  PrivateAdminDashboardPayrollManagementSalaryHistoryRoute: typeof PrivateAdminDashboardPayrollManagementSalaryHistoryRoute
  PrivateAdminDashboardStaffManagementTypeRoute: typeof PrivateAdminDashboardStaffManagementTypeRoute
  PrivateAdminDashboardContractManagementIndexRoute: typeof PrivateAdminDashboardContractManagementIndexRoute
  PrivateAdminDashboardLeaveManagementIndexRoute: typeof PrivateAdminDashboardLeaveManagementIndexRoute
  PrivateAdminDashboardManagementReportIndexRoute: typeof PrivateAdminDashboardManagementReportIndexRoute
  PrivateAdminDashboardOtherRequestsManagementIndexRoute: typeof PrivateAdminDashboardOtherRequestsManagementIndexRoute
  PrivateAdminDashboardPayrollManagementIndexRoute: typeof PrivateAdminDashboardPayrollManagementIndexRoute
  PrivateAdminDashboardRecruitmentManagementIndexRoute: typeof PrivateAdminDashboardRecruitmentManagementIndexRoute
  PrivateAdminDashboardStaffManagementIndexRoute: typeof PrivateAdminDashboardStaffManagementIndexRoute
  PrivateAdminDashboardTimekeepingShiftSchedulingIndexRoute: typeof PrivateAdminDashboardTimekeepingShiftSchedulingIndexRoute
  PrivateAdminDashboardStaffManagementDetailIdRoute: typeof PrivateAdminDashboardStaffManagementDetailIdRoute
  PrivateAdminDashboardTimekeepingShiftSchedulingExplanationManagementIndexRoute: typeof PrivateAdminDashboardTimekeepingShiftSchedulingExplanationManagementIndexRoute
  PrivateAdminDashboardTimekeepingShiftSchedulingShiftManagementIndexRoute: typeof PrivateAdminDashboardTimekeepingShiftSchedulingShiftManagementIndexRoute
  PrivateAdminDashboardTimekeepingShiftSchedulingTimekeepingManagementIndexRoute: typeof PrivateAdminDashboardTimekeepingShiftSchedulingTimekeepingManagementIndexRoute
}

const PrivateAdminDashboardRouteChildren: PrivateAdminDashboardRouteChildren = {
  PrivateAdminDashboardDashboardLazyRoute:
    PrivateAdminDashboardDashboardLazyRoute,
  PrivateAdminDashboardPayrollManagementDataSummaryRouteRoute:
    PrivateAdminDashboardPayrollManagementDataSummaryRouteRouteWithChildren,
  PrivateAdminDashboardLeaveManagementLeaveRequestManagementRoute:
    PrivateAdminDashboardLeaveManagementLeaveRequestManagementRoute,
  PrivateAdminDashboardOtherRequestsManagementBusinessTripManagementRoute:
    PrivateAdminDashboardOtherRequestsManagementBusinessTripManagementRoute,
  PrivateAdminDashboardOtherRequestsManagementOvertimeManagementRoute:
    PrivateAdminDashboardOtherRequestsManagementOvertimeManagementRoute,
  PrivateAdminDashboardOtherRequestsManagementRemoteWorkManagementRoute:
    PrivateAdminDashboardOtherRequestsManagementRemoteWorkManagementRoute,
  PrivateAdminDashboardOtherRequestsManagementTrainingRegistrationRanagementRoute:
    PrivateAdminDashboardOtherRequestsManagementTrainingRegistrationRanagementRoute,
  PrivateAdminDashboardPayrollManagementPayrollCalculationRoute:
    PrivateAdminDashboardPayrollManagementPayrollCalculationRoute,
  PrivateAdminDashboardPayrollManagementPayslipFeedbackRoute:
    PrivateAdminDashboardPayrollManagementPayslipFeedbackRoute,
  PrivateAdminDashboardPayrollManagementSalaryHistoryRoute:
    PrivateAdminDashboardPayrollManagementSalaryHistoryRoute,
  PrivateAdminDashboardStaffManagementTypeRoute:
    PrivateAdminDashboardStaffManagementTypeRoute,
  PrivateAdminDashboardContractManagementIndexRoute:
    PrivateAdminDashboardContractManagementIndexRoute,
  PrivateAdminDashboardLeaveManagementIndexRoute:
    PrivateAdminDashboardLeaveManagementIndexRoute,
  PrivateAdminDashboardManagementReportIndexRoute:
    PrivateAdminDashboardManagementReportIndexRoute,
  PrivateAdminDashboardOtherRequestsManagementIndexRoute:
    PrivateAdminDashboardOtherRequestsManagementIndexRoute,
  PrivateAdminDashboardPayrollManagementIndexRoute:
    PrivateAdminDashboardPayrollManagementIndexRoute,
  PrivateAdminDashboardRecruitmentManagementIndexRoute:
    PrivateAdminDashboardRecruitmentManagementIndexRoute,
  PrivateAdminDashboardStaffManagementIndexRoute:
    PrivateAdminDashboardStaffManagementIndexRoute,
  PrivateAdminDashboardTimekeepingShiftSchedulingIndexRoute:
    PrivateAdminDashboardTimekeepingShiftSchedulingIndexRoute,
  PrivateAdminDashboardStaffManagementDetailIdRoute:
    PrivateAdminDashboardStaffManagementDetailIdRoute,
  PrivateAdminDashboardTimekeepingShiftSchedulingExplanationManagementIndexRoute:
    PrivateAdminDashboardTimekeepingShiftSchedulingExplanationManagementIndexRoute,
  PrivateAdminDashboardTimekeepingShiftSchedulingShiftManagementIndexRoute:
    PrivateAdminDashboardTimekeepingShiftSchedulingShiftManagementIndexRoute,
  PrivateAdminDashboardTimekeepingShiftSchedulingTimekeepingManagementIndexRoute:
    PrivateAdminDashboardTimekeepingShiftSchedulingTimekeepingManagementIndexRoute,
}

const PrivateAdminDashboardRouteWithChildren =
  PrivateAdminDashboardRoute._addFileChildren(
    PrivateAdminDashboardRouteChildren,
  )

interface PrivateRouteChildren {
  PrivateLogoutRoute: typeof PrivateLogoutRoute
  PrivateAdminDashboardRoute: typeof PrivateAdminDashboardRouteWithChildren
  PrivateAdminIndexRoute: typeof PrivateAdminIndexRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateLogoutRoute: PrivateLogoutRoute,
  PrivateAdminDashboardRoute: PrivateAdminDashboardRouteWithChildren,
  PrivateAdminIndexRoute: PrivateAdminIndexRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  PrivateRoute: PrivateRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRoute,
  UnauthenticatedRoute: UnauthenticatedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
